livechat/livechat-public-docs

rest-api/_reports.md

Change to the tag[] argument – it did not included square brackets [] and the tag request without them is not valid.

`tag[]` argument updated for _reports.md

---

site/content/rest-api/groups.md

We noticed that group status is returned in list all groups endpoint.
This was not reflected in the sample response.

Update group sample response to include group status

---

.gitignore
README.md
site/content/agent-app-widgets/js-api.md

Hey, I've reordered the docs so Hugo displays them better. I've also changed some wording around code blocks, because it was written as if they appear below the text, instead of beside it.
For eg:
> Set the `Widget placement` to `Chat details` and provide the initial state JSON, eg.: 
vs
> Set the `Widget placement` to `Chat details` and provide the initial state JSON.
with an additional explanation in the example:
> Example of initial state JSON for "Chat details":
I've also added `package-lock.json` to `.gitignore` since it's automatically generated. And changed a line in `README` with the correct command to run the docs.

Reorder docs so it looks better

---

site/content/rest-api/archives.md

Fixing the description explaining the page limitation, available in REST APIs /archives section

Fix for page description in /archives

---

content/index.mdx
content/management/configuration-api/index.mdx
content/management/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/customer-chat-api/index.mdx
content/monetization/index.mdx
content/monetization/partner-program-api/index.mdx

- Updated postman links; now the environment is downloaded once someone imports a collection, and we no longer need the environment.json file
- Small fixes in the send_event method
- Moved Partner Program API to the monetization category

Postman links & Partner Program API

---

content/management/configuration-api-v2/index.mdx

There was a redundant block quote left inside a `<CodeResponse>` from https://developers.livechatinc.com/docs/management/configuration-api-v2/#create-a-ticket, which caused a pretty nasty visual bug:
Removing that has fixed it:

remove redundant block quote in CodeResponse from "Create a ticket" in Configuration API v2

---

content/management/configuration-api/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx

- `check goals` added to table
- `timestamp` replaced with `seen_up_to` + correct reference in tables
- push and webhook `events_marked_as_seen`
- more info in the `get_form` method description 
- file event parameters updated 
- correct response for get chat threads in Agent API

Fixes in Customer and Agent Chat APIs

---

content/extending-ui/extending-chat-widget/customer-sdk/index.mdx

https://unpkg.com/@livechat/customer-sdk@2 isn't valid, changed it to https://unpkg.com/@livechat/customer-sdk, so that user would be correctly redirected to the newest version while using
PR in chat-widget: https://github.com/livechat/chat-window/pull/4917

update unpkg customer-sdk packages address in docs

---

content/messaging/chat-sdk/index.mdx

- links in Section component didn't work

Fixing links in Chat SDK docs

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.2/index.mdx

This new webhook supports following filters:
`chat_member_ids`
`only_my_chat`
Allowed additional data:
`chat_properties`

v3.2: add webhook follow_up_requested

---

.gitignore
content/management/configuration-api/index.mdx
content/management/configuration-api/v3.2/index.mdx

- Added links to "Register webhook" in the Create Bot Agent and Update Bot Agent methods, as the `.filters` param isn't described in these methods

Added a note on filters in Create and Update Bot Agent methods

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx

Method **Add User to Chat** has a new optional parameter `require_active_thread`. 
This is a copy of the branch _API-5396-add-user-require-active_ created to have a feature branch.
Proofreading done.

API-5396 Add User to Chat require_active_thread

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

Copy of the branch: _API-5443-update-docs-about-id-in-group-chooser_ made to have a feature branch.
There's a new parameter `id` in the **Form field** data structure (`fields.answer.id` for the `group_chooser` field type).  It's a unique identifier for each option Customers can choose. This `id` is also returned by the **Get Form** method.

API- 5443 ID in group_chooser

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- Added missing errors to Customer API (rtm&web, 3.1, 3.2)
- Changed errors formatting
- Updated the description of the `send_event` method - mentioned it's possible to chat without joining the chat. (Agent API, RTM & Web, 3.1, 3.2)
- Added a similar note to chat_user_added (Agent and Customer RTM 3.1, 3.2)

Updates in errors, send event, and chat_user_added push

---

content/getting-started/installing-livechat/ios-widget/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
gatsby-browser.js
src/utils/index.js

- Fix in scopes (incorrect roles)
- Fix in Get Archives (`filters` param)
- Added opening of the chat widget when clicking a link in **Getting started > Installing LiveChat > LiveChat for iOS > Getting help**

Fix scopes & open chat widget

---

src/utils/index.js

The search was broken because of the old address "livechatinc.com". Replaced with "livechat.com"

Fix search

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-5735-thread-created_at)
- [Jira](https://livechatinc.atlassian.net/browse/API-5735)
Replace `order` + `timestamp` with `created_at` in Thread data structure

Created_at in Thread data structure

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-5739-remove-get-chat-threads-summary)
Remove get chat threads summary from v3.2

remove get-chat-threads-summary from both apis

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/chat-order)
Deprecate `order` in `chat` object - more details in the comments of https://livechatinc.atlassian.net/browse/API-6333

deprecate chat order field

---

content/management/changelog/index.mdx
content/management/configuration-api/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/payloads/other-structures/aa_chatSummary.json
content/messaging/agent-chat-api/payloads/other-structures/aa_thread.json
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/payloads/other-structures/ca_thread.json
content/messaging/customer-chat-api/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6209-queue-transfers-restore)
- [Jira](https://livechatinc.atlassian.net/browse/API-6209)
- Changelog
- API versions
- Web & RTM
- New content

Restore API-6209: update queue and transfers.

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-list-chats-and-list-archives)
- describe `next_page_id`, `chat-summaries`, and `previous_page_id` in List Chats (Agent APi)
- change `filters.date_from` and `filters.date_to` in List Archives

Fixes in List Chats and List Archives

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/payloads/events/aa_file_v3_3.json
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/payloads/events/ca_file_v3_3.json
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6521)
- [Jira](https://livechatinc.atlassian.net/browse/API-6521)
Support for `alternative_text` for images within File Events. Only available in v3.3 of agent-api and customer-api.
- Changelog
- API versions
- Web & RTM
New param in File Event
- New content

API-6521 documented alternative_text for images in file event

---

content/messaging/agent-chat-api/index.mdx
src/components/core/SideNav/SideNav.js
src/components/extensions/Errors.js
src/components/extensions/Scopes.js
src/components/extensions/Table.js
src/components/extensions/index.js
src/constant/index.js
src/templates/page.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-2201)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2201)
Created a new component - `Errors`. It mirrors the `Scopes` component.
- New feature

Added Errors component

---

content/management/configuration-api/index.mdx
content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6944-approve-agent)
- [Jira](https://livechatinc.atlassian.net/browse/API-6944)
Update scopes required by `approve_agent` - previous `billing:rw` was a virtual scope that would never be published. `subscription_manage` is virtually the same as `billing:rw` but is published :)
- Changelog
- API versions
- Web & RTM

API-6944: approve_agent: update required scopes

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-5804-auto-access-rules)
- [Jira](https://livechatinc.atlassian.net/browse/API-6698)
Docs for the auto access rules feature: the rules can be managed via the new methods in configuration-api v3.3.
There was already an attempt to release the feature in the past, hence the "old" branch name.
- Changelog
- API versions
- Web & RTM
- New content in configuration v3.3: new section Auto access rules
- Changelog entry for v3.3
- New feature

API-6698: document auto access

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.1/index.mdx
content/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
payloads/messaging/v3.2/agent-chat-api/other-structures/thread.json
payloads/messaging/v3.2/customer-chat-api/other-structures/thread.json
payloads/messaging/v3.3/agent-chat-api/other-structures/thread.json
payloads/messaging/v3.3/customer-chat-api/other-structures/thread.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6878-restricted-access)
- [Jira](https://livechatinc.atlassian.net/browse/API-6878)
Update `restricted_access` documentation.
In agent-api v3.2+ it's string field with reason for restriction.
In customer-api there's no restricted_access in any version.
- Changelog ✅
- Web & RTM ✅
Backwards-incompatible but very important.

Update 'restricted_access' documentation

---

content/messaging/apple-business-chat/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-naming-in-abc-docs)
Change:
>  "CSP" reference to "MSP" for Messaging Service Provider
as requested.

Change naming in Apple Business Chat docs

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
payloads/messaging/v3.3/agent-chat-api/events/richMessage.json
payloads/messaging/v3.3/customer-chat-api/events/richMessage.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6468-rich-message-button-target)
- [Jira](https://livechatinc.atlassian.net/browse/API-6468)
Add new `target` property to rich message's `button`.
- Changelog ✅ 
- Web & RTM ✅
New parameter in existing structure.
- New content 
- New feature

API-6468: Add `target` property to RM `button`

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/adjust-configuration-endpoints)
Prefix new customer configuration endpoints with `get_`. Use full "configuration", not "config".
- Changelog ✅ 
- API versions ✅ 
- Web & RTM ✅ 
- **Table:** Available methods/webhooks/pushes ✅ 
- **Table:** Specifics 
Update methods in dev preview.
- Breaking change ✅

customer/v3.3: Prefix configuration endpoints with verbs

---

content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/retries-for-pushes)
Clarify there're no retries for pushes.
Agent & Customer RTM Chat API, all versions

Address no retries for pushes

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
payloads/messaging/v3.3/agent-chat-api/other-structures/chat.json
payloads/messaging/v3.3/agent-chat-api/other-structures/chatSummary.json
payloads/messaging/v3.3/agent-chat-api/users/customer.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7272)
- [Jira](https://livechatinc.atlassian.net/browse/API-7272)
Extended the customer object's `last_visit` with `ended_at` date (to match `started_at`)
- Changelog
- API versions
- Web & RTM
- New content

API-7272 added ended_at to last_visit for customer

---

content/extending-chat-widget/javascript-api/v1.0/index.mdx

Fix the old JS API example, so it uses the proper callback

Fix hide example to use proper callback in old JS API docs

---

content/extending-chat-widget/javascript-api/index.mdx

Fix typo `chata` -> `chat`

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

start/resume_chat: `active`
- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7592-resume-and-offline-thread)
- [Jira](https://livechatinc.atlassian.net/browse/API-7592)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-7592: activate -> resume chat

---

content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/bot-timezone)
One of possible values in `fields` (`list_bot` / `get_bot`) is not documented.

add info about timezone in get-bot and list-bots methods

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx
payloads/management/v3.3/configuration-api/responses/bots/getBot.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8109-separate-webhooks-from-bots)
- [Jira](https://livechatinc.atlassian.net/browse/API-8109)
Bot webhooks can no longer be registered using `create_bot` and `update_bot`, and they are not returned by `get_bot`.
- Changelog
- API versions
- Web & RTM
- Changes in an existing feature in the dev preview version of API (v3.3)

API-8109 updated bot docs v3.3

---

content/management/configuration-api/index.mdx
content/management/configuration-api/v2.0/index.mdx
content/management/configuration-api/v3.1/index.mdx
content/management/configuration-api/v3.3/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.1/index.mdx
content/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2587)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2587)
Messaging and Configuration APIs required changes to unify the nomenclature for request and response objects. 
Changes can be summarized as:
Agent Chat API, Customer Chat API, Configuration API:
- **Events** > request "field" changed to "parameter"
- **Methods** > response "parameter" changed to "field, 
request "request object" changed to "field"
- **Pushes** > push payload "object" changed to "field"
Configuration API:
- **Webhooks** > webhook payload "object" changed to "field"
- API versions - **3.3, 3.2, 3.1, and 2.0 applicable only for Configuration API**
- Both Web & RTM APIs
- Updated: **Events, Methods, Pushes, and applicable only for …

[DPS-2587] Refactor parameter/field in Messaging + Configuration API nomenclature

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx

drop `customer_` from rule names
give explicit example of how reorder works
highlight that at least one rule needs to be specified
- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8565-update_auto_access/management/configuration-api/v3.3/#auto-access)
- [Jira](https://livechatinc.atlassian.net/browse/API-8565)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-8565: rename reorder_ to update_auto_access

---

content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/feature/remove-customer-prefix-from-aar-examples)
Remove `customer_` prefix from Auto access rules documentation code examples. It is a small leftover after https://github.com/livechat/livechat-public-docs/pull/868

Remove 'customer_' prefix from AAR code examples

---

content/management/changelog/index.mdx
content/management/configuration-api/index.mdx
content/management/configuration-api/v3.1/index.mdx
content/management/configuration-api/v3.3/index.mdx
payloads/management/v3.3/configuration-api/responses/webhooks/listWebhookNames.json
payloads/management/v3.3/configuration-api/responses/webhooks/listWebhooks.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8114-update-wh-filters)
- [Jira](https://livechatinc.atlassian.net/browse/API-8114)
Add new webhook filter `chat_presence`. 
Add new webhook additional data `chat_presence_user_ids`.
- Changelog ✅
- Web & RTM ✅
- **Table:** Available methods/webhooks/pushes ✅
- New content
- New feature

API-8114: new WH filters/additional data

---

content/management/configuration-api/index.mdx
content/management/configuration-api/v3.1/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/management/configuration-api/v3.4/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8636-limit-chats-count)
- [Jira](https://livechatinc.atlassian.net/browse/API-8636)
Add info about limit for value of `max_chats_count` param in create/update bot methods.
Autoformatted tables to look nicer.
- New content

Add info about max_chats_count limit for bots

---

content/extending-chat-widget/customer-sdk/index.mdx
content/extending-chat-widget/customer-sdk/v1.0/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-property-name
- Rename the wrong property in the chat transcript feature recipe
- Move example to the proper version

CustomerSDK: Rename the wrong property in the chat transcript feature recipe

---

payloads/data-reporting/v3.2/reports-api/responses/chats/agentsChattingDuration.json
payloads/data-reporting/v3.2/reports-api/responses/chats/tags.json
payloads/data-reporting/v3.3/reports-api/responses/chats/agentsChattingDuration.json
payloads/data-reporting/v3.3/reports-api/responses/chats/tags.json
payloads/data-reporting/v3.3/reports-api/responses/chats/totalChats.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/misc-fixes-23-04)
- Added the missing `name` field in the Reports API responses v3.2 & v3.3

Add name field in Reports API responses v3.2, v3.3

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8750-new-pushes-documentation)
- [Jira](https://livechatinc.atlassian.net/browse/API-8750)
Information on new pushes in 3.4 -> thread_deleted, threads_deleted, chat_deleted
No much info about them, are props seem self-explanatory. Change only i Agent-Chat-API.
Didn't found info about pushes in changelog, so no changes there 
- New content

Feature/api 8750 agent-api new pushes - thread_deleted,threads_deleted,chat_deleted

---

content/management/changelog/index.mdx
content/management/configuration-api/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/management/configuration-api/v3.4/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.4/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
payloads/management/v3.4/configuration-api/responses/webhooks/listWebhookNames.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-9179-no-access-change-inactive-chat)
- [Jira](https://livechatinc.atlassian.net/browse/API-9179)
Update methods/pushes/webhooks that modify chat access (`(grant|revoke)_chat_access`, `chat_access_(granted|revoked)`, new `chat_access_updated`).
Note that `transfer_chat` works only for active chats.
Fix available webhooks and their filters.
Fix payload of `chat_transferred` push.

API-9179: no access change in inactive chat

---

src/pages/authorization/global-accounts/index.mdx

Fix for: 
https://developers.livechat.com/docs/authorization/global-accounts#account

Fix path to image in Global Accounts doc

---

src/pages/extending-chat-widget/custom-identity-provider/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-2639)
Customers seems to miss the information about the need of data parsing before passing it to the widget. I've tried to catch more attention on that sentence by making it **bold**. Additionally, I've noticed that we don't mention the required shift from snake_case to camelCase explicitly.

[CW-2639] Emphasise the need of parsing the data from endpoint in Custom Identity Provider

---

src/pages/authorization/authorizing-api-calls/index.mdx

As suggested on #platform-docs we're adding information about encoding account ID and PAT into base64.

Mention base64 in PAT auth

---

src/pages/authorization/sign-in-with-livechat/index.mdx
src/pages/data-reporting/reports-api/index.mdx
src/pages/data-reporting/reports-api/v3.2/index.mdx
src/pages/data-reporting/reports-api/v3.4/index.mdx
src/pages/messaging/chat-sdk/index.mdx

- Users can now use PATs to authorize calls to Reports API.
- A couple typo/link fixes

Mention PATs in Reports API

---

src/pages/extending-agent-app/agent-app-sdk/index.mdx
src/pages/getting-started/livechat-apps/index.mdx
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v2.0/index.mdx
src/pages/management/configuration-api/v3.1/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/v3.1/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/customer-chat-api/index.mdx
src/pages/messaging/customer-chat-api/v3.1/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.4/index.mdx

- Fix copy explaining token prefixes
- Update OAuth2.0 to 2.1

Fix copy explaining token prefixes and update OAuth2.0 to 2.1

---

src/pages/management/configuration-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/customer-chat-api/v3.4/index.mdx

1. list webhooks requires "owner client_id"
2. Missing semicolon causing the curl to fail
3. Adjusted curl (Postman wouldn't allow previous one to get imported)

Fixed errors in curls

---

src/pages/extending-chat-widget/custom-identity-provider/index.mdx

Scroll down for the link to the deploy preview.
n/a
@bolchowka noticed that the code example in [Customer Identity Provider](https://developers.livechat.com/docs/extending-chat-widget/custom-identity-provider#without-caching) (w/o caching) won't work because `fetchToken()` function does not return a promise - it only assigns one. The additional return should resolve the confusion 😉

Fix code sample in Customer Identity Provider

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

- [Jira]()
In v3.5 and v3.4, Register Webhook's description missed the "Make sure" phrase.

Improve copy in Register Webhooks

---

_redirects
src/pages/extending-chat-widget/chat-widget-moments/index.mdx
src/pages/extending-chat-widget/visitor-sdk/index.mdx
src/pages/management/webhooks/v3.1/index.mdx
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/DED-113)
Added redirects for 404 links from [this document](https://docs.google.com/spreadsheets/d/1l863BPCevayKOfGl7QGgTdLNV_XospMpFy2I6BfMPFk/edit#gid=0) and fixed broken links in the docs.

[DED-113] Fix 404 and broken links in the docs

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

https://62c80388346cb770fac880a4--livechat-public-docs.netlify.app
- [Jira](https://livechatinc.atlassian.net/browse/API-10726)
Two changes:
1. adding new scope `--my:ro` for reading properties from your own namespace
2. reverting the `--all:ro` scopes instead of `--all:rw` (temporary problem in the past)
The changes in the code are already deployed to the production (this morning) - we had to act very quickly when it comes to requiring additional scopes.

API-10726: update scopes required by list_group_properties and list_license_properties

---

src/pages/data-reporting/reports-api/index.mdx
src/pages/data-reporting/reports-api/v3.5/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-11012)
Note about filters validation - we don't say anywhere that if filters are provided, some kind of from/to filter must be provided (and we can provide only one). We didn't have an explicit error for this (we returned: `RFC3339 date format required for %s.from`), but it's going to change and ``filters` must contain `filters.from/to` or `filters.greetings.from/to` or `filters.surveys.from/to`` will be returned in such situation 

API-11012 add note about from/to filters

---

.github/workflows/preview.yml

N/A
N/A
- Use additional `actions/setup-node@v2` for preview gh action to always use specific node version and take advantage of npm dependencies caching
- Install dependencies using `npm ci` to always resolve deps tree from package-lock.json which is used for cache fingerprinting
- Use already installed `netlify-cli` and remove the redundant installation
Example results show a ~2 minute drop in action executing time. Still, the main bottleneck is 15-17 minutes of build time, but hey, its stilll a little bit faster 😄 

Cache npm dependencies for preview gh action

---

src/pages/management/webhooks/index.mdx
src/pages/management/webhooks/v3.5/index.mdx

New entry for `agent_deleted` webhook was added in the docs for v3.4+ but the old description of this webhook still exists so I suggest to remove it. Wdyt?

fix: removed duplicated agent_deleted webhook in v3.4+

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-11290)
Add missing documentation for agent's `login_status` field.

API-11290: document agent's `login-status`

---

payloads/management/v3.5/configuration-api/responses/agents/getAgent.json
payloads/management/v3.5/configuration-api/responses/agents/listAgents.json
src/pages/management/changelog/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-11296)
we're exposing account_id in agent getters, i'm not sure if there's a place we can put a description of the field as it is not modyfiable.

API-11296: account_id in list_agents/get_agent

---

src/pages/management/changelog/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx
src/pages/management/webhooks/v3.5/index.mdx
src/pages/messaging/agent-chat-api/v3.5/rtm-pushes/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-9264)
We're changing how webhooks and pushes for modification of auto access rules work.
Instead of multiple pushes in 3.5, we're introducing a new push/webhook - auto_accesses_updated that aggregates all changes done in single action as a single push/webhook instead of old behavior, which resulted in multiple pushes from one action.

API-9670 add description for auto_accesses_updated

---

src/pages/messaging/agent-chat-api/changelog/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-11796)
`get_chat` in Agent API v3.4+ now validates access to thread.

API-11796: describe fix for get_chat access

---

src/pages/management/changelog/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-11995)
Remove "At least one Agent must have the `normal` priority." requirement in Create group method.

API-11995 Removed create group priority requirement

---

src/pages/messaging/apple-messages-for-business/index.mdx

https://63db94345db0cb348ed415bc--livechat-public-docs.netlify.app
- [Jira](https://livechatinc.atlassian.net/browse/AA-13871)
We've added support to the new [Authentication Message](https://register.apple.com/resources/messages/msp-rest-api/new-oauth), which will work on devices running iOS 16, iPadOS 16 or macOS 13. The changes support backward compatibility with the older devices.

AA-13871: Apple Messages for Business Authentication new Authentication Message

---

src/pages/extending-chat-widget/customer-sdk/index.mdx

https://63fc9ae73c0ada01f81ada8c--livechat-public-docs.netlify.app/extending-chat-widget/customer-sdk#using-a-script-tag---umd-module-hosted-on-unpkgs-cdn
No Jira related to this task
We are about to release small changes to the CustomerSDK – **changes should be released next week on production**, probably on 2023-02-21. 
Changes will include a fix to `getUrlInfo` method, mainly to the `urlDetails.imageUrl`. Before the fix, this method could sometimes return a URL with a double protocol in front of the img address. 
Because the change also bumps the version of CustomerSDK, I also bumped it in the link to UMD module.

adjusting customerSDK public docs to future changes

---

src/pages/messaging/customer-chat-api/changelog/index.mdx
src/pages/messaging/customer-chat-api/v3.6/index.mdx

https://63fe0860b51feb19505af6c4--livechat-public-docs.netlify.app
- [API-12277](https://livechatinc.atlassian.net/browse/API-12277)
We've changed the response format of `get_dynamic_configuration` in v3.6+ to support non-LC widgets as default widgets.
[API-12277]: https://livechatinc.atlassian.net/browse/API-12277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

API-12277: update get_dynamic_configuration

---

src/configs/redoc/global-accounts-api/spec.yml

https://640af8507e0ecc6f98576924--livechat-public-docs.netlify.app/authorization/global-accounts-api#tag/Accounts/paths/~1accounts~1%7Baccount_id%7D/delete
[ACC-2209][]
[ACC-2209]: https://livechatinc.atlassian.net/browse/ACC-2209
I updated required scopes for two of the endpoints. This change is related to [ACC-2209][] that will remove some of the scopes from product admins. Therefore, for some of the accounts, more granular scopes will have to be used.

ACC-2209 update authentication and add request body

---

src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-12676)
Fix scopes description in Add User To Chat.
Scope `chats--all:rw` allows access to all chats only for the requester, so when adding other agents using token with this scope, they still have to have access to that chat.
Scope `chats--access:rw` requires the user's access, not the requester's access to match the chat access.

API-12676: fix scopes description in Add User To Chat

---

src/constant/index.js
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

- [Jira]()
As agreed with Paweł, the new Bot section has been added to the Web and RTM Agent Chat API. The section is needed as many devs ask about it or have problems with calling methods as bots.

NO-DED adding x-agent-id to Web and RTM Agent Chat API

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

Specify that `owner_client_id` is required for webhooks management iff the request is authorized with PAT.

Specify when owner_client_id is required for wh mgmt

---

src/pages/messaging/customer-chat-api/changelog/index.mdx
src/pages/messaging/customer-chat-api/rtm-pushes/index.mdx
src/pages/messaging/customer-chat-api/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-pushes/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.3/rtm-pushes/index.mdx
src/pages/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.4/rtm-pushes/index.mdx
src/pages/messaging/customer-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.6/rtm-pushes/index.mdx
src/pages/messaging/customer-chat-api/v3.6/rtm-reference/index.mdx

- Don't have one
We are removing `customer_page_updated` from all the Customer API versions, because it's unused and useless and generates a lot of data.

remove 'customer_page_updated' push from all versions of Customer-API

---

src/pages/authorization/sign-in-with-livechat/index.mdx

We had inprecise information in authorization documentation in Log in with LiveChat section. I have added correct notes for response types and data that are returned during Accounts token exchange

Fix authorization docs

---

netlify.toml

This code affects page indexing in the PRODUCTION environment. Deploy previews by default on Netlify have a noindex tag added to the header.
- [Jira]()

(HOTFIX) Website indexing in Google

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-13656)
Due to security reasons we no longer fall back to the token's client_id when authorizing via Bearer token for properties, webhooks and bot templates management.

API-13656: Make owner_client_id required in some methods

---

src/pages/messaging/customer-chat-api/changelog/index.mdx
src/pages/messaging/customer-chat-api/v3.6/index.mdx
src/pages/messaging/customer-chat-api/v3.6/rtm-reference/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CDP-275)

feat: send_greeting_postback customer's method

---

src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

Jira: https://livechatinc.atlassian.net/browse/CDP-234

feat: agent-api: remove method create_customer v3.6

---

src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/changelog/index.mdx
src/pages/messaging/customer-chat-api/v3.6/rtm-pushes/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/ME-561)

messaging: add event_preview
