rest-api/_reports.md

moved "simultaneous chats" report closer to other chat reports

updated "simultaneous chats" report placement

---

rest-api/_visitors.md

Changed links from faulty ones (/build-an-integration#webhooks) to proper ones (/build-integration/#webhooks)

Fixed links on _visitors.md

---

visitor-sdk/_callbacks.md
visitor-sdk/_changelog.md
visitor-sdk/_introduction.md

Synchronize files from livechat-public-docs

---

agent-app-extension/_advanced-use.md
agent-app-extension/_authorization.md
agent-app-extension/_js-api.md
boilerplate/_introduction.md

support 'authorize:false' flag in boilerplate

---

site/content/agent-app-widgets/js-api.md

Valid JSON in docs

---

site/content/agent-app-widgets/js-api.md

Adds a new property to the `Button` widget which controls if the app's iframe is opened after clicking the button or not. More details can be found here: https://github.com/livechat/my.livechatinc.com/pull/9763

Add new button 'openApp' config

---

site/content/js-api/methods.md
site/content/js-api/tracking-code.md

Description of ChatWidget JS API methods:
- set_visitor_name
- set_visitor_email

JS API - set_visitor_name set_visitor_email description

---

site/content/how-to-monetize-apps/_index.md
site/content/how-to-monetize-apps/monetization.md

Added:
-an excerpt
- "LiveChat" in alt tag in images

SEO update to the How to monetize apps doc

---

package.json
scripts/feature-branch.js

Currently feature branch is created but with `baseUrl=/docs` which doesn't help when navigating the app. This script will prefix the `baseUrl` with proper branch name.

(DPS-842) Add feature branch script

---

site/content/chat-widget-moments/changelog.md
site/content/chat-widget-moments/moments-in-livechat.md
site/content/chat-widget-moments/moments-sdk.md
site/content/chat-widget-moments/resources.md

Updated Chat Widget Moments docs with:
- UMD build usage
- Handling query param `moments-title`
- Building moments using Agent App MessageBox integration

[CW-1302] Feature/Chat Widget Moments update

---

site/content@beta/customer-chat-rtm-api/_index.md
site/content@beta/customer-chat-rtm-api/contact-us.md
site/content@beta/customer-chat-rtm-api/data_structures.md
site/content@beta/customer-chat-rtm-api/events.md
site/content@beta/customer-chat-rtm-api/introduction.md
site/content@beta/customer-chat-rtm-api/link.svg
site/content@beta/customer-chat-rtm-api/methods.md
site/content@beta/customer-chat-rtm-api/pushes.md
site/content@beta/customer-chat-rtm-api/users.md
site/content@beta/customer-chat-web-api/_index.md
site/content@beta/customer-chat-web-api/contact-us.md
site/content@beta/customer-chat-web-api/data_structures.md
site/content@beta/customer-chat-web-api/events.md
site/content@beta/customer-chat-web-api/introduction.md
site/content@beta/customer-chat-web-api/link.svg
site/content@beta/customer-chat-web-api/methods.md
site/content@beta/customer-chat-web-api/users.md
site/content@beta/customer-chat-web-api/webhooks.md

- Customer Chat RTM API
- Customer Chat Web API

the new Customer Chat API 

---

content/docs/data-reporting/reports-api/index.mdx
content/docs/management/configuration-api-v2/index.mdx

- minor fix for configuration api v2

reports-api-v2

---

content/management/configuration-api/index.mdx
package-lock.json

Changed methods formatting and some paths.

Configuration API v3.1 

---

site/content/rest-api/tickets.md
site/content@beta/rest-api/tickets.md

https://livechatinc.atlassian.net/browse/API-4366

API-4366: Add `source_id` option to GET /tickets

---

content/messaging/agent-chat-api/rtm-reference/index.mdx

Fixed formatting for Agent Chat RTM API

agent chat rtm api (fixed formatting)

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx

- Other common structures
- Users 
- Events
in Agent Chat API

Other data structures, Users formatted in RTM and Web

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx

System messages in Agent and Customer
Proof in Agent

Proofreading Agent API

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx

- send_event updated
- send_file removed
- some other minor changes

Methods updates

---

content/management/configuration-api/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx

- fixed links in tables
- updated the file object
- added a link in the get_chats_summary method

Fixed links

---

content/management/configuration-api/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
package-lock.json

Added a new subsection in RTM (Customer and Agent) on data centers.

Data centers subsection

---

content/messaging/agent-chat-api/index.mdx
content/messaging/customer-chat-api/index.mdx

Small update to the definition of the upload_file method.

Update to upload_file definition

---

content/getting-started/authorization/index.mdx
content/getting-started/authorization/sign-in-with-livechat/index.mdx
content/getting-started/guides/messaging-apis-in-practice/index.mdx

- response format in **Authorization**
- removed the example from **Sign in with LiveChat**
- specified the token proprietor in **Messaging APIs in practice**

Getting Started fixes

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx

- Added refreshed Errors sections
- Gathered all headers in one table
- Fixed incorrect nesting in menu

Errors in docs

---

content/extending-ui/extending-chat-widget/rich-messages/index.mdx

Language check for the document

Rich messages docs proofreading

---

content/extending-ui/extending-agent-app/agent-app-sdk/index.mdx
content/getting-started/authorization/index.mdx
content/getting-started/index.mdx
content/management/configuration-api-v2/index.mdx
content/management/configuration-api/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx

- remove old beta-docs links
- fix several links in webhooks

Fix webhook links 

---

content/management/configuration-api/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx

- updated links and headings in the Triggering actions table

Triggering actions updated

---

content/monetization/partner-program-api/index.mdx

~Do not merge yet - I just want to get a preview link ;)~
Edit: ready to be released :)

Updated Partner Program API Docs

---

content/messaging/chat-sdk/index.mdx

- Added a few additional steps + links to GH and NPM
- Changed the hierarchy as the menu wasn't properly displayed

Improve instructions in Chat SDK docs

---

content/messaging/go-sdk/go-sdk.mdx

We're mentioning the new LiveChat Go SDK in our public docs
**feature branch:** https://developers.labs.livechatinc.com/docs/feature/lc-go-sdk
(Messaging -> LiveChat Go SDK)

LiveChat Go SDK

---

content/management/changelog/index.mdx
content/management/configuration-api/v2.0/index.mdx
content/management/configuration-api/v3.2/index.mdx

2 new methods:
- Delete group properties
- Delete license properties

Delete group and license properties

---

content/getting-started/authorization/faq/index.mdx

A new document: **FAQ related to authorization.** 
Requested by tech support.

Authorization FAQ

---

content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

Updated the description of `greeting_canceled` with another case when this push is sent.

Updated the description of greeting_canceled

---

content/messaging/apple-business-chat/index.mdx

Docs for Apple Business Chat integration public API

Apple Business Chat integration docs

---

gatsby-browser.js
src/templates/page.js

Jira: https://livechatinc.atlassian.net/browse/DPS-1234
FB: https://developers.labs.livechatinc.com/docs/feature/dps-1234

(DPS-1234) Docs heading paddings

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

**Introduction -> Authentication** was updated. 
Now it's **Access -> Authorization/Server pinging/Scopes**

Update the Authentication section

---

content/messaging/agent-chat-api/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

Removed some legacy links to beta-docs

Fix broken links in Authentication section

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

System messages:
- routing.assigned_signed_out
- routingassigned_remotely_signed_out
- routing.assigned_deleted
- routing.assigned_disconnected
Pushes:
- customer_updated

Update in system messages and pushes

---

content/data-reporting/reports-api/index.mdx
src/components/core/prism.css

- added missed chat to the documentation
- added fix for "response" code to gatsby-highlight class
```
width: -webkit-fill-available;
width: -moz-available;
```
**Before:**
**After**

Added missed chats to doc

---

content/monetization/partner-program-api/index.mdx

Please do not merge it yet, PR made just for live preview

Updates in Partner Program API

---

gatsby-browser.js
src/utils/index.js

https://livechatinc.atlassian.net/browse/DPS-1583
Making sure window is checked before loading amplitude.

(DPS-1583) Fix build for loading amplitude

---

content/monetization/billing-api/index.mdx

Mentioned `per_account` param in Billing API docs.
https://livechatinc.atlassian.net/browse/DPS-1657

[DPS-1657] per_account in Billing API 

---

content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

https://livechatinc.atlassian.net/browse/API-5465

API-5465 Clarify when thread_id is present in chat-user-added/removed.

---

content/extending-ui/extending-chat-widget/v2.0/customer-sdk/index.mdx

Proofreading of the new Customer SDK

Customer SDK proofreading

---

content/extending-ui/extending-chat-widget/rich-messages/index.mdx

add missing elements.buttons.text to the RMs documentation

add missing elements.buttons.text to the RMs documentation

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

Method **Get URL Details** (Customer API, Web & RTM) returns a new parameter, `image_original_url`.

New param image_original_url in Get URL details

---

content/extending-ui/extending-chat-widget/chat-widget-moments/index.mdx
content/extending-ui/extending-chat-widget/rich-messages/index.mdx
content/extending-ui/extending-chat-widget/v2.0/customer-sdk/index.mdx
content/extending-ui/extending-chat-widget/visitor-sdk/index.mdx

Documentation for New Customer SDK version
- Move old documentation under v1.0
- New documentation available under v2.0 as a dev preview
https://developers.labs.livechatinc.com/docs/feature/update-customer-sdk/extending-ui/extending-chat-widget/v2.0/customer-sdk/

[CW-1753] New Customer SDK docs

---

content/extending-ui/extending-chat-widget/v2.0/customer-sdk/index.mdx

- bump `customer-sdk` package version due to the `customer-auth` dependency update
- mention the above in the changelog
- add the required scopes and redirect URI whitelist to the configuration steps
- mention `react-native-livechat` in the `React Native` section to cover some use cases

CustomerSDK v2.0 docs update

---

content/extending-ui/extending-chat-widget/customer-sdk/index.mdx
content/extending-ui/extending-chat-widget/v2.0/customer-sdk/index.mdx

lock customerSDK unpkg versions

lock customerSDK unpkg versions

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx

Added:
- description for Set Away Status
- description for Set Routing Status
- description for `away` in Login
Updated: 
- Changelog
[Feature branch](https://developers.labs.livechatinc.com/docs/feature/API-5352-agent-login-away-proofreading) recommended 👌🏻

Poofreading of feature/API-5352-agent-login-away

---

content/extending-ui/extending-chat-widget/customer-sdk/index.mdx

lock package version for npm in customerSDK v1.0

CW-1817: lock package version for npm in customerSDK v1.0

---

content/management/configuration-api/index.mdx
content/management/configuration-api/v2.0/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/index.mdx

Described API versioning in **Messaging Overview > APIs Overview > API versioning** and in the **Versioning** section of each API document.
**feature branch:** https://developers.labs.livechat.com/docs/feature/versioning

Describe API versioning

---

content/management/configuration-api/v2.0/index.mdx

I'm still not sure about the description. Please propose a better alternative if needed.

Add active prop to greeting docs

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- added tables **Request** and **Response** for Rich message, System Message and Custom events
- collected all system messages in a table with links and changed their heading to h4 so that they disappear from the menu
Feature branch: https://developers.labs.livechatinc.com/docs/feature/describe-events

Describe events

---

gatsby-config.js

FB: https://developers.labs.livechat.com/docs/feature/fix-sitemap/

(NO-DPS) Fix double docs in sitemap

---

content/getting-started/authorization/index.mdx
content/monetization/app-review-process/index.mdx

Jira: https://livechatinc.atlassian.net/browse/DPS-1682

(DPS-1682) Prompt=consent param

---

content/extending-ui/extending-chat-widget/rich-messages/index.mdx
content/extending-ui/extending-chat-widget/visitor-sdk/index.mdx

remove vistiorSDK from the menu and inform that it is deprecated

remove vistiorSDK from the menu and inform that it is deprecated

---

content/extending-ui/extending-chat-widget/visitor-sdk/index.mdx

link to customerSDK 1.0 to be safer as advised by @bkubiak

link to customerSDK 1.0 to be safer

---

content/extending-ui/extending-chat-widget/v2.0/customer-sdk/index.mdx

Update the docs to reflect updates in the newest CustomerSDK 2.0.0-beta.2

CustomerSDK 2.0.0-beta.2

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx

https://livechatinc.atlassian.net/browse/API-6004

API-6004: changed chat access management methods/pushes/webhooks in v3.2

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.2/index.mdx

https://livechatinc.atlassian.net/browse/API-5879

API-5879 Remove mentions of follow_up_requested webhook

---

content/extending-ui/extending-agent-app/design-system/index.mdx

[Feature branch](https://developers.labs.livechat.com/docs/feature/embed-design-system)
Form located in **Extending UI > Extending Agent App > Design System**

(DPS-1717) Embed static form built with Design System

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.2/index.mdx

rendered at https://developers.labs.livechat.com/docs/feature/API-5804-auto-access-rules/management/configuration-api/v3.2/#auto-access (scroll up a tiny bit)

API-5804: auto access rules

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx

All user-generated content will be hosted on livechat-files.com.

API-5873: Replace livechat-static with livechat-files

---

content/data-reporting/reports-api/index.mdx
content/extending-ui/extending-agent-app/product-cards/index.mdx
content/getting-started/guides/webhook-apps/index.mdx
content/management/configuration-api/index.mdx
content/management/configuration-api/v2.0/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/platform-docs-fixes)
- Broken link in Product Cards docs
- Misleading method desc in Data & reports API
- Misleading Configuration API name in Building webhook apps tutorial
- Typo
- Missing header

Platform docs fixes

---

content/monetization/billing-api/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-1839-1895)
- [Jira](https://livechatinc.atlassian.net/browse/dps-1839)
- [Jira](https://livechatinc.atlassian.net/browse/dps-1895)
Copy of  #649 
- allow developer to set recurring charge in months time frame
- direct charge update implementation
- New content

DPS direct charge update + allow developer to set recurring charge in months time frame

---

content/messaging/agent-chat-api/index.mdx
src/components/core/icons.js
src/components/extensions/Scopes.js
src/components/extensions/index.js
src/constant/index.js
src/templates/page.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-1799)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-1799)
Build scopes table from a component
- Changelog
- API versions
- Web & RTM
- New feature

(DPS-1799) Scopes component

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/payloads/events/custom.json
content/messaging/agent-chat-api/payloads/events/file.json
content/messaging/agent-chat-api/payloads/events/filled-form.json
content/messaging/agent-chat-api/payloads/events/message.json
content/messaging/agent-chat-api/payloads/events/rich-message.json
content/messaging/agent-chat-api/payloads/events/system-message.json
src/components/extensions/CodeBlocks.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-1798-new)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-1798)
New way of loading JSON payloads to the mdx.
- New feature

(DPS-1798) New component for JSON response, use it with events

---

content/management/configuration-api/v3.2/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/specify-agent-priority)
Described how priority options in API (`first`, `normal`, `last` correspond with the options in the LiveChat App)

Mention agent and bot group priority

---

content/management/configuration-api/v3.2/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-bot-priority)
Updated group priority for bots

Updated group priority for bots

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-5737-list_chats-pagination)
- [Jira](https://livechatinc.atlassian.net/browse/API-5720)
In list_chats use standard pagination, as in other API methods

API-5737 list_chats pagination

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6227-customer_application)
- [Jira](https://livechatinc.atlassian.net/browse/API-6227)
Extend customer login with application info required for internal stats
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-6227: extend customer login with application info

---

content/monetization/how-to-monetize-apps/index.mdx
gatsby-config.js
plugins/gatsby-remark-placeholders/index.js
plugins/gatsby-remark-placeholders/package-lock.json
plugins/gatsby-remark-placeholders/package.json
plugins/gatsby-remark-placeholders/parsers/index.js
plugins/gatsby-remark-placeholders/parsers/link.js
plugins/gatsby-remark-placeholders/placeholders.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-1953)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-1953)
Allow adding placeholders to mdx. 
For now support for:
{{DEVELOPER_CONSOLE_URL}}
{{LIVECHAT_HOME_URL}}
This will convert to:
```
<a href="https://developers.livechat.com/console/" target="_blank">Developer Console</a>
<a href="https://www.livechat.com" target="_blank">LiveChat</a>
```
- New feature

(DPS-1963) New plugin with link parser, use in monetization

---

gatsby-browser.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-redirects-in-authorization)
Fix redirects 
- Bug fix

Fix redirects in authorization

---

content/default-credentials.md

- [Feature branch](https://developers.labs.livechat.com/docs/feature/default-credentials)
A file with default credentials, such as names, ids, access tokens, etc. Use it in code snippets.
- New content

File with default credentials

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/extend-get-archives-request)
Extend the request of Get Archives. Update responses of Get/List Archives to match the requested resource.

Extended List/Get archives

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

Added info about `addon` greeting property
- Changelog
- API versions
- Web & RTM

API-6274: Add info about 'addon' in responses with greeting

---

content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

This is a newly introduced property, just in the preview version so not much to change besides adding this information.

Add info that greeting's addon property is optional

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-5745-list-archives-pagination)
- [Jira](https://livechatinc.atlassian.net/browse/API-5745)

New pagination in list-archives

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6450-archives-highlights)
- [Jira](https://livechatinc.atlassian.net/browse/API-6450)

API-6450 Archives highlights

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/payloads/other-structures/aa_chatSummary.json
content/messaging/agent-chat-api/v3.2/payloads/other-structures/aa_thread.json
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.2/index.mdx
content/messaging/customer-chat-api/v3.2/payloads/other-structures/ca_thread.json
content/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

https://github.com/livechat/livechat-public-docs/pull/683
https://github.com/livechat/livechat-public-docs/pull/681
https://github.com/livechat/livechat-public-docs/pull/687

Revert commits 683, 681, 687

---

content/management/changelog/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/payloads/other-structures/aa_chat.json
content/messaging/agent-chat-api/payloads/other-structures/aa_chatSummary.json
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/payloads/other-structures/ca_chat.json
content/messaging/customer-chat-api/payloads/other-structures/ca_chatSummary.json
content/messaging/customer-chat-api/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/chat-order-and-highlights)
- feature/chat-order
- feature/API-6450-archives-highlights
- New content

Chat order and highlights

---

content/extending-ui/extending-chat-widget/customer-sdk/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-customer-sdk-cdn-url)

Fix CDN url to the Customer SDK script

---

content/management/configuration-api/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/customer-chat-api/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-1339)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-1339)
Embedded buttons to Postman collection(v3.2)
- New content

Embedded Postman collection buttons

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/bring-back-API-5745)
#672 
- New content

Pagination in List Archives

---

content/extending-ui/extending-chat-widget/chat-widget-moments/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/new-moments-capabilities/)
- [Jira](https://livechatinc.atlassian.net/browse/CW-1580)
Describe new moments methods: `setExternalLink` and `sendSystemMessage`

Describe new moments methods: setExternalLink and sendSystemMessage

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/customer-login-response)
Update data returned in customer's login response.
- Changelog
- API versions
- Web & RTM
- New content

v3.2: update customer login response.

---

content/extending-ui/extending-chat-widget/customer-sdk/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/customer-sdk-fix-ratechat)
`rateChat` and `cancelRate` are fixed in `v2.0.1`

Update CustomerSDK changelog to the newest version

---

content/management/configuration-api/index.mdx
content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/get_group-align-request-response)

Align request with response in get_group

---

src/components/core/seo.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/update-widget-snippet-code/)
Update the Chat Widget snippet code to the newest version.

Update Chat Widget snippet code to the newest version

---

content/management/changelog/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-2121)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2121)
Restructured the Changelog in Agent Chat API as a proof of concept.

(DPS-2121) Clean up Changelog v3.2

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6794-params-rename)
- [Jira](https://livechatinc.atlassian.net/browse/API-6794)
Rename parameter names in some v3.3 methods

Rename Agent API parameters in some v3.3 methods

---

content/management/configuration-api/v2.0/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6263-greeting-announcement)
- [Jira](https://livechatinc.atlassian.net/browse/API-6263)
Add new `subtype` property to greeting configuration.
- Changelog
- API versions
- Web & RTM
New param in v2.0 docs.
- New content
- New feature

API-6263: Add `subtype` property to greetings

---

content/index.mdx
content/monetization/app-review-process/index.mdx
content/monetization/billing-api/index.mdx
plugins/gatsby-remark-placeholders/index.js
plugins/gatsby-remark-placeholders/parsers/index.js
plugins/gatsby-remark-placeholders/parsers/text.js
plugins/gatsby-remark-placeholders/placeholders.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2028)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2028)
New text parser for the placeholder plugin which replaces e.g. {{NUMBER_OF_CUSTOMERS}} with 30,000.
This can be extended by adding new placeholders.
- New feature

(DPS-2028) Text parser for the placeholder plugin

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6795-methods-params-rename)
- [Jira](https://livechatinc.atlassian.net/browse/API-6756)

API-6795 Rename methods params

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6796-params-rename-confapi)
- [Jira](https://livechatinc.atlassian.net/browse/API-6796)
Rename parameters in v3.3 methods

Rename parameters in conf-api v3.3

---

content/management/configuration-api/index.mdx
content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/edit-list-bots)
Added a detailed method description explaining how the response may differ in different situations.
- v3.3 Configuration API ✅
- v3.2 Configuration API 

Method description for List Bots

---

README.md
package.json
scripts/version.js
src/constant/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2160)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2160)
2 scripts:
1. `make-stable` e.g. `npm run version -- --type=make-stable --newVersion=3.3 --exclude=customer-chat-api` (make version 3.3 stable, current stable version will become legacy) 
Options:
`--group`: (default: DEFAULT), for chat widget use `--group=chat-widget`
`--exclude`: e.g. `--exclude=agent-chat-api,customer-chat-api`  
2. `new` e.g. `npm run version -- --type=new --newVersion=3.5 --fromVersion=3.1` (create new version 3.5, based on files from 3.1)
Options:
`--group`: (default: DEFAULT), for chat widget use `--group=chat-widget`
`--exclude`: e.g. `--exclude=agent-chat-api,customer-chat-api`  
- New feature

(DPS-2160) Version scripts

---

content/management/changelog/index.mdx
content/management/configuration-api/index.mdx
content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6888-bot-timezones)
- [Jira](https://livechatinc.atlassian.net/browse/API-6888)
Add `timezone` parameter to bot management methods

Bot timezone settings

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/rate-limits)
- [Jira](https://livechatinc.atlassian.net/browse/API-6826)
General description of rate limits (without detailed info with numbers).

add info about rate limits in agent-api

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
payloads/messaging/v3.2/agent-chat-api/other-structures/chatSummary.json
payloads/messaging/v3.3/agent-chat-api/other-structures/chatSummary.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/misc-changes)
Minor fixes + extended desc of chat_transferred in agent-api
- Changelog
- API versions
- Web & RTM

misc updates

---

content/categories.json
content/messaging/references/default-properties/index.mdx
content/messaging/references/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/default-properties)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2048)
New document, Default properties in Messaging > References > Default properties.
- New content

Default properties

---

content/management/changelog/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-auto-access-changelog)
Change heading from Groups to Auto access.

Changed heading in Configuration API Changelog

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.1/index.mdx
content/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
src/constant/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-2222)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2222)
Refactored documents (Agent and Customer Chat APIs) to use the Errors component.

(DPS-2222) Refactor Errors

---

src/components/core/components.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2234-fix-sidenab)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2234)
Add ellipsis for the sidenav
- Bug fix

(DPS-2234) Add ellipsis to sidenav

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6540-cw-endpoints)
- [Jira](https://livechatinc.atlassian.net/browse/API-5353)

API-6540 Add dynamic_config, config and localization methods

---

content/messaging/js-sdk/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/lc-sdk-js)
Add mention of LC SDK JS (similar to the one in Go)
- New content

Add LC JS SDK page

---

src/components/core/Rating/index.js
src/components/core/Rating/modal.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-2266)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2266)
Added a modal with an iframe displaying a Google Form.
- New feature

(DPS-2266) Improvements for Rating component

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6905-notifications-incoming_message_for_focused_chat)
- [Jira](https://livechatinc.atlassian.net/browse/API-6905)
- Changelog
- API versions
- Web & RTM
- New content
- New feature

add notifications.incoming_message_for_focused_chat agent property

---

content/messaging/references/default-properties/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7030-translation-props)
- [Jira](https://livechatinc.atlassian.net/browse/API-7030)
- Changelog
- API versions
- Web & RTM
- New content
- New feature

API-7030: translation properties

---

content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7147-login-scopes)
- [Jira](https://livechatinc.atlassian.net/browse/API-7147)
We need to require more scopes in `login` due to information in pushes.
In near future (and v3.3 only), we will provide a way to choose subscription on specific pushes so required scopes will depend on the request payload.

require more scopes in login due to information in pushes (all versions)

---

content/messaging/customer-chat-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/extend-desc-config-methods)
Describes the response of the Get Dynamic Configuration method as requested.
- Customer Chat Web API v3.3

Describe the response of Get Dynamic Config

---

src/components/core/components.js
src/components/core/header.js
src/components/core/version.js
src/components/extensions/CodeBlocks.js
src/constant/index.js

- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

added promo bar about txtlss

---

content/data-reporting/reports-api/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7089-agents_chatting-report)
- [Jira](https://livechatinc.atlassian.net/browse/API-7089)

API-7089 Document new agents_chatting_duration report

---

src/constant/index.js

- [Jira](https://livechatinc.atlassian.net/browse/ACC-361)

ACC-361 updated agents-bot--all:ro role

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
payloads/messaging/v3.3/agent-chat-api/users/customer.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6735-customer-related-pushes)
- [Jira](https://livechatinc.atlassian.net/browse/API-6735)
v3.3: update customer-related pushes/traffic according to project https://livechatinc.atlassian.net/wiki/spaces/PAT/pages/990674947/customer-related+pushes.
- Changelog ✅
- Web & RTM ✅
- **Table:** Available methods/webhooks/pushes ✅
- **Table:** Specifics ✅
Add new methods and pushes, remove some existing pushes.
- New content
- New feature

API-6735: v3.3: customer-related traffic changes

---

content/data-reporting/reports-api/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-agents_chatting_duration-report-authorization)

Fix agents_chatting_duration report authorization

---

content/getting-started/authorization/scopes/index.mdx
src/constant/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7510-properties-configuration-scope)
- [Jira](https://livechatinc.atlassian.net/browse/API-7510)
Add new scope `properties--configuration:rw` which will be required for new properties configuration endpoints (v3.3+).
n/a
- New content
- New feature

API-7510: Add scope properties--configuration:rw

---

content/management/limits/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/hide-limits)
As requested per support team. Hidden temporarily. 

Hide Limits

---

content/extending-chat-widget/customer-sdk/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/CW-2157)
- [Jira](https://livechatinc.atlassian.net/browse/CW-2157)
Added missing docs for 2.0.2 and 2.0.3 customer-sdk versions and also for 2.0.4 which essentialy just updates the missing docs of previous verions.
- Changelog
- API versions
- Web & RTM
- New content

CW-2157 Update CustomerSDK docs with the newest changelog

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7619-sort_by-list_customers)
- [Jira](https://livechatinc.atlassian.net/browse/API-7619)

API-7619 Add sort_by to list_customers

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7419-include_customers_without_chats-list_customers)
- [Jira](https://livechatinc.atlassian.net/browse/API-7419)

API-7419 Add include_customers_without_chats filter to list_customers

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7600-document-subtyp-for-greeting)
- [Jira](https://livechatinc.atlassian.net/browse/API-7600)
Documented new greeting property.

API-7600: Document new greeting property

---

content/extending-chat-widget/javascript-api/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/CW-2217)
- [Jira](https://livechatinc.atlassian.net/browse/CW-2217)
Update URL for the embedded interactive playground in Chat Widget JS API documentation.

CW-2217: Update CW JS API Playground URL

---

src/components/core/header.js

- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

took down txtlss

---

src/components/core/components.js
src/components/core/header.js
src/components/core/version.js
src/components/extensions/CodeBlocks.js
src/constant/index.js

- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

fixed spacings

---

content/extending-chat-widget/customer-sdk/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/customer-sdk-recipes-section/
- [Jira](https://livechatinc.atlassian.net/browse/CW-2227)
New "Recipes" section in the Customer SDK docs.

new customerSDK Recipes section, add links to properties docs

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7063-list-routing-statuses)
- [Jira](https://livechatinc.atlassian.net/browse/API-7063)
- New content

API-7063 v3.3: add list_routing_statuses to agent-api.

---

content/extending-chat-widget/customer-sdk/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/CW-1602)
- [Jira](https://livechatinc.atlassian.net/browse/CW-1602)
As title says, added yet another recipe to CustomerSDK docs.
- Changelog
- API versions
- Web & RTM
- New content
- New feature

[CW-1602] CustomerSDK: Add hard limit handling example to recipes

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7392-list_threads-from-to-filters)
- [Jira](https://livechatinc.atlassian.net/browse/API-7392)

API-7392 Add list_threads from/to filters

---

content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/update-customer_page_updated-push)
Remove `referrer` from the customer_page_updated push. Reported internally.
- API versions
- Web & RTM

Remove referrer from customer_page_updated push

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/v3.1/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx

- [Feature branch] https://developers.labs.livechat.com/docs/feature/API-7561-customer_session_fields_updated_wh/
- [Jira] https://livechatinc.atlassian.net/browse/API-7274
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-7561: new wh 3.3 configuration docs updated

---

content/messaging/references/default-properties/index.mdx

- [Feature branch] https://developers.labs.livechat.com/docs/feature/API-7898-routing_offline_message
- [Jira] https://livechatinc.atlassian.net/browse/API-6709
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-7898 routing.offline_message

---

content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
src/constant/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-6567-New_error_type_when_registering_request_while_performing_shutdown)
- [Jira](https://livechatinc.atlassian.net/browse/API-5572)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-6567: service unavailable error

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx
payloads/management/v3.3/configuration-api/index.js
payloads/management/v3.3/configuration-api/responses/webhooks/listWebhookNames.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7729-list-webhook-names)
- [Jira](https://livechatinc.atlassian.net/browse/API-7729)
Docs for new method `list_webhook_names`
- New content

API-7729 Add list_webhook_names method

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/references/default-properties/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7895-offline-mesg-tweaks)
- [Jira](https://livechatinc.atlassian.net/browse/API-7895)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-7895: offline mesg tweaks

---

content/extending-chat-widget/rich-messages/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-rm-links/)
Fix the links to the Chat APIs

Fix the links in Rich Messages docs

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx
payloads/management/v3.3/configuration-api/index.js
payloads/management/v3.3/configuration-api/responses/webhooks/getWebhooksState.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7738-manage-wh-state)
- [Jira](https://livechatinc.atlassian.net/browse/API-7738)
Add new methods for managing webhooks' state.
- Changelog ✅
- Web & RTM ✅
- **Table:** Available methods/webhooks/pushes N/A
- **Table:** Specifics N/A
New methods.
- New content
- New feature

API-7738: add methods for webhooks state management

---

content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7915-predicted-agent)
- [Jira](https://livechatinc.atlassian.net/browse/API-7659)
- New content

v3.3: New param in CustoemrAPI::GetPredictedAgent.

---

content/data-reporting/reports-api/index.mdx
content/data-reporting/reports-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7904-tags-report)
- [Jira](https://livechatinc.atlassian.net/browse/API-7904)

Mark distribution as required in tags reports

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7864-document-new-flter-for-list-customers)
- [Jira](https://livechatinc.atlassian.net/browse/API-7864)
- Changelog
- API versions
- Web & RTM
- New content

API-7864: Document new filter

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-7632-chat-transferred-webhook)
- [Jira](https://livechatinc.atlassian.net/browse/API-7484)
- New content

Add ChatTransferred webhook.

---

content/authorization/authorizing-api-calls/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/improve-authorization-docs)
A more precise description of how to authorize with PATs.

Changes in the Authorizing API calls doc

---

content/management/configuration-api/v2.0/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/dps-2584)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2584)
As requested by tech support.

Add scopes to Config API v2

---

content/getting-started/app-guides/in-app-upgrades/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/update-webhook-payload-inapp-resources)
Update webhook payload.

Updated webhook payload

---

content/management/configuration-api/v3.3/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8069-fix-props-access-docs)
- [Jira](https://livechatinc.atlassian.net/browse/API-8069)
Clarify how public properties' access works.
n/a

Describe public property access better

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-5625-customer-updated)
- [Jira](https://livechatinc.atlassian.net/browse/API-5625)
- New content

Update CustomerUpdated description and payload.

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.3/index.mdx
payloads/management/v3.3/configuration-api/responses/webhooks/getWebhooksState.json
payloads/management/v3.3/configuration-api/responses/webhooks/listWebhooks.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8104-type-in-webhooks-3-3)
Copy of #837 
- New content

API-8104 type in webhooks v3.3

---

content/authorization/authorizing-api-calls/index.mdx
content/getting-started/app-guides/app-authorization/index.mdx
src/constant/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fixes-in-authorization)
Reported on Slack

Describe customers:own, add and fix links

---

content/management/references/license-properties/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8070-document-new-license-property)
- [Jira](https://livechatinc.atlassian.net/browse/API-8070)
- Changelog
- API versions
- Web & RTM
- New content

API-8070: Document new license property

---

content/management/configuration-api/v3.3/index.mdx

- [[Feature branch]](https://developers.labs.livechat.com/docs/feature/API-8253-default_value_in_property_config)
- [[Jira]](https://livechatinc.atlassian.net/browse/API-8185) 
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-8253: default value in lc3 props

---

src/configs/redoc/livechat-accounts-api/spec.yml

- [Feature branch](https://developers.labs.livechat.com/docs/feature/update-global-accounts-spec-jan-2021)
Requested by tech support on the channel.
- New content

Mention PATs and Implicit flow

---

content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

Add missing license_expired reason in customer_disconnected reasons

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.1/index.mdx
content/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8146-too-many-requests)
- [Jira](https://livechatinc.atlassian.net/browse/API-8146)
new error for all versions (unfortunately)

add error too_many_requests for all versions of customer-api

---

content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/service-unavailable-reason)
We have added a new type of disconnect reason `service_temporarily_unavailable`. I have also fixed `internal` reason description. For more details please check: https://github.com/livechat/customer-api/pull/462#issue-574887082

add service_temporarily_unavailable disconnect reason

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/v3.3/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.3/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [[Feature branch]](https://developers.labs.livechat.com/docs/feature/API-8177-pagination)
- [[Jira]](https://livechatinc.atlassian.net/browse/API-8094)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-8177 pagination described

---

src/components/core/SideNav/SideNav.js
src/components/core/components.js
src/components/core/header.js
src/configs/redoc/livechat-accounts-api/config.js
src/templates/page.js

- [Jira](https://livechatinc.atlassian.net/browse/DPS-2678)
- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2678)
Promo Banner for live coding session. Text has to be changed. 
- New feature

(DPS-2678) Promo banner in docs

---

src/components/core/components.js
src/components/core/version.js
src/components/extensions/CodeBlocks.js
src/constant/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-version)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2678)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(DPS-2678) Promo banner layout fixes

---

content/monetization/how-to-monetize-apps/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2757)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2757)
Describe withdrawal rules for monetary prizes.
- New content

Withdrawal rules for monetary prizes

---

content/monetization/how-to-monetize-apps/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2757-fix)
Fix typo

Fix typo in DPS-2755

---

src/components/core/components.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/missing-items-in-sidebar-bug)
- Changelog
- API versions
- Web & RTM
- New content
- Bug fix

(NO-DPS) Missing elements in sidebar - bug fix

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8312-customer-monitoring-level)
- [Jira](https://livechatinc.atlassian.net/browse/API-8312)
- New content

Rename customer_push_level to customer_monitoring_level. Revisit levels.

---

src/components/core/components.js
src/components/core/header.js
src/components/core/redoc.css
src/components/core/version.js
src/components/extensions/CodeBlocks.js
src/configs/redoc/livechat-accounts-api/config.js
src/constant/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/remove-info-banner)

(NO-DPS) Remove info banner

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
content/messaging/customer-chat-api/changelog/index.mdx
content/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8540-push-filtering)
- [Jira](https://livechatinc.atlassian.net/browse/API-8540)
Describe changes from https://livechatinc.atlassian.net/browse/API-7352 and https://livechatinc.atlassian.net/browse/API-7282.
- Changelog ✅
- RTM ✅
- **Table:** Available methods/webhooks/pushes ✅
- New content
- New feature

API-8540: describe push filtering changes

---

src/components/core/fonts.css

- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

Rating component

---

src/components/core/Rating/index.js
src/components/core/Rating/star.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/add-css-selector-to-rating-component)
For better discoverability in Full Story
- New feature

Add ID to Rating component

---

scripts/version.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2816)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2816)
Add support for `make-stable` and `new` to Reports API.
- New feature

Add reports-api to version.js

---

content/authorization/sign-in-with-livechat/index.mdx
content/monetization/app-review-process/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/accounts-sdk-mobile-app)
Requested on Slack.
- New content

Note about Accounts SDK and LiveChat mobile

---

content/authorization/sign-in-with-livechat/index.mdx
content/management/configuration-api/index.mdx
content/management/configuration-api/v3.4/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/misc-fixes-16-04)
- Configuration API v3.3 and v3.4

Fixes in Configuration API

---

content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
content/messaging/customer-chat-api/rtm-reference/index.mdx
content/messaging/customer-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-login-example)
Small tweak of example payload

Fix example payload for login v3.3+

---

content/management/configuration-api/index.mdx
content/monetization/index.mdx
payloads/management/v3.3/configuration-api/responses/agents/listAgents.json
payloads/management/v3.4/configuration-api/responses/agents/listAgents.json

- [Feature branch](https://developers.labs.livechat.com/docs/feature/contentfixes)
Small content fixes:
- https://developers.livechat.com/docs/management/configuration-api/#update-auto-access changed groups to "groups" in sample response
- https://developers.livechat.com/docs/management/configuration-api/#list-webhooks corrected request sample
- updated link to the Console in Monetization Overview
- added "name" field in the response for List Agents method in 3.3 and 3.4 configuration API

content fixes

---

gatsby-config.js
src/components/core/SideNav/SideNav.js
src/hooks/useScrollSpy.js
src/utils/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2899)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2899)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(DPS-2899) Send scroll info to GA from docs

---

gatsby-config.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2898)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2898)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(DPS-2898) Changed datalayer to filter GA events in GTM

---

content/getting-started/installing-livechat/android-widget/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/update-livechat-for-android-docs)
Add missing info (taken from the project's README)

Update LiveChat for Android docs

---

package.json
src/pages/_app.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2940)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2940)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(DPS-2940) Migrate GA plugin 

---

content/getting-started/installing-livechat/android-widget/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/lc-android-clear-chat-session)
https://github.com/livechat/chat-window-android/commit/240e91208a83eeff62fac4973ca06ee77330b1a0#diff-b335630551682c19a78[…]8ac04c6bf87428ed5106870f5

Mention session cleaning

---

content/management/changelog/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8933-chat-access-set)
- [Jira](https://livechatinc.atlassian.net/browse/API-8933?oldIssueView=true)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-8933: correct which webhook was actually removed

---

content/extending-chat-widget/chat-widget-moments/index.mdx
content/extending-chat-widget/customer-sdk/index.mdx
content/extending-chat-widget/customer-sdk/v1.0/index.mdx
content/extending-chat-widget/customer-sdk/v2.0/index.mdx
content/extending-chat-widget/index.mdx
content/extending-chat-widget/javascript-api/index.mdx
content/extending-chat-widget/javascript-api/v1.0/index.mdx
content/extending-chat-widget/javascript-api/v2.0/index.mdx
content/extending-chat-widget/rich-messages/index.mdx
content/extending-chat-widget/visitor-sdk/index.mdx
src/constant/index.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/customer-sdk-v3)

Update Customer SDK docs in preparation for stable release

---

content/messaging/customer-chat-api/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/patch-1-missing-auth-header-send-event-1)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

Added missing Auth header in method: `customer/action/send_event`

---

content/authorization/authorizing-api-calls/index.mdx

Copy of `patch-1-creating-a-customer-flow`

Added `token_type` to response parameters

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.4/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8684-add-info-about-accesible-threads)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-8684: Add info about accesible threads

---

content/management/limits/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8585-add-info-about-limits-for-access-rules)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

API-8585: Add auto access rules limits

---

src/pages/monetization/how-to-monetize-apps/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/DPS-2975)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(DPS-2975) Wrong text placement in docs (How to monetize apps) 

---

src/components/core/components.js

- [Jira](https://livechatinc.atlassian.net/browse/DPS-2973)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(DPS-2973) Docs are not displayed properly on mobile devices

---

scripts/buildArticles.js
src/configs/articles.json

- [Jira](https://livechatinc.atlassian.net/browse/DPS-2974)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(DPS-2974) Sidebar encounters some problems with redirecting into selected object

---

src/pages/getting-started/app-guides/chat-webhooks/index.mdx
src/pages/getting-started/app-guides/in-app-upgrades/index.mdx

- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(NO-DPS) Fixing minor migration bugs

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.4/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

agents
bots
auto accesses
- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8724-config-events)
- [Jira](https://livechatinc.atlassian.net/browse/API-8724)
[agents ticket](https://livechatinc.atlassian.net/browse/API-8714)
[auto access ticket](https://livechatinc.atlassian.net/browse/API-8733)
I'll fix the formatting once we settle on the wording 😉 
- Changelog
- API versions
- Web & RTM
- New content

Describe configuration pushes and webhooks.

---

content/management/changelog/index.mdx
content/management/configuration-api/v3.4/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8704-group-push-wh)
- [Jira](https://livechatinc.atlassian.net/browse/API-8704)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

group changes webhooks and pushes

---

content/extending-agent-app/agent-app-sdk/index.mdx
content/extending-chat-widget/customer-sdk/index.mdx
content/getting-started/index.mdx
content/index.mdx
content/management/configuration-api/index.mdx
src/components/extensions/Headings.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/misc-fixes-04-06-2021)
Links, punctuation, formatting.

(NO-DPS) Misc fixes

---

content/management/configuration-api/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/management/configuration-api/v3.4/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/approve-agent-note)
As reported on Slack.

(NO-DPS) Elaborate on Agent Approve

---

content/extending-chat-widget/chat-widget-moments/index.mdx

- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

Change license to license_id in Chat Widget Moments

---

src/components/extensions/Headings.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2984)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2984)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

(DPS-2984) Platform toolkits containers are not adjusting properly to the width

---

.github/pull_request_template.md

(NO-DPS) Changed PR template

---

content/management/changelog/index.mdx
content/management/configuration-api/index.mdx
content/management/configuration-api/v3.1/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/management/configuration-api/v3.4/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-8995-add-info-about-supervisor-priority)
- Changelog
- API versions
- Web & RTM
- New content
- New feature
- Bug fix

Document 'default_group_priority' and 'supervisor' priority

---

content/authorization/authorizing-api-calls/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/mention-helpdesk)
Mentioned HelpDesk API in our docs.

Mentioned HelpDesk in authorization

---

src/components/core/components.js
src/components/core/header.js
src/components/core/version.js
src/components/extensions/CodeBlocks.js
src/contexts/index.js
src/templates/page.js

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-2769)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-2769)

(DPS-2769) Create generic banner component 

---

next.config.js
package.json

- [Jira](https://livechatinc.atlassian.net/browse/DPS-2887)
Before: 
After:

(DPS-2887) Fix code highlighting

---

src/pages/getting-started/index.mdx

(NO-DPS) Missing placeholder

---

next.config.js

(NO-DPS) New default reading time 

---

src/components/extensions/Headings.js

(NO-DPS) Bug fix - non-loading images 

---

content/getting-started/app-guides/app-webhooks/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-1344)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-1344)
Update app webhooks with payment ones

(DPS-1344) Update App webhooks

---

scripts/buildArticles.js
src/configs/articles.json

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3037)

(DPS-3037) Articles script improvements 

---

next.config.js
src/components/core/SideNav/SideNav.js
src/components/core/header.js
src/components/core/prism.css
src/components/extensions/CodeBlocks.js
src/components/extensions/Headings.js
src/components/extensions/index.js
src/hooks/useArticlesInCategory.js

Fixes after wolf:
- links
- css for sidebar
- code highlighting
- trailing slashes

Wolf fixes 2

---

content/data-reporting/changelog/index.mdx
content/data-reporting/reports-api/index.mdx
content/data-reporting/reports-api/v3.2/index.mdx
content/data-reporting/reports-api/v3.4/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-9074)
- [Jira](https://livechatinc.atlassian.net/browse/API-9074)
Provides information about required scopes for Reports API.

API-9074: scopes for Reports API

---

content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.4/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-9096-add-user-req-active-thread)
- [Jira](https://livechatinc.atlassian.net/browse/API-9093)

v3.4: update add_user_to_chat description.

---

content/authorization/authorizing-api-calls/index.mdx
src/configs/redoc/customer-accounts-api/spec.yml

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-9086-identity-transfer)
- [Jira](https://livechatinc.atlassian.net/browse/API-8928)
Describe new identity transfer flow in customer-sso.

API-9086: Add identity transfer for customer tokens

---

content/authorization/authorizing-api-calls/index.mdx
content/extending-chat-widget/javascript-api/index.mdx
content/extending-chat-widget/javascript-api/v2.0/index.mdx
content/getting-started/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/misc-fixes-06-07-21)
- Fix typos
- Comment out examples with `off()` to reduce confusion and frustration of devs who copy and paste those snippets (JS API)

(NO-DPS) Miscellaneous fixes

---

content/data-reporting/changelog/index.mdx
content/data-reporting/reports-api/v3.4/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/v3.4/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-9064-event_types)
- [Jira](https://livechatinc.atlassian.net/browse/API-9064)

API-9064 Document events.types => event_types.(values|exclude_values)

---

content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-path-to-image)

Fixed path to image

---

src/components/core/SideNav/SideNav.js
src/hooks/useArticlesInCategory.js

(NO-DPS) Prepare sidebar for /docs path

---

content/management/changelog/publish-todo.md
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.4/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-9134-update-scopes-my)
- [Jira](https://livechatinc.atlassian.net/browse/API-9134)

Update scopes in chat-related methods.

---

content/getting-started/livechat-apps/webhook-apps/index.mdx
content/management/configuration-api/index.mdx
content/management/configuration-api/v2.0/index.mdx
content/management/configuration-api/v3.1/index.mdx
content/management/configuration-api/v3.2/index.mdx
content/management/configuration-api/v3.4/index.mdx
content/management/index.mdx
content/messaging/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/DPS-3084)
- [Jira](https://livechatinc.atlassian.net/browse/DPS-3084)
Currently, **Messaging Overview** contains a [section about the Configuration API](https://developers.livechat.com/docs/messaging/#configuration-api), which doesn't belong there. I moved the section to Management Overview and extended it.

(DPS-3084) Revamp Management Overview

---

content/data-reporting/changelog/index.mdx
content/data-reporting/reports-api/v3.4/index.mdx
content/messaging/agent-chat-api/changelog/index.mdx
content/messaging/agent-chat-api/index.mdx
content/messaging/agent-chat-api/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.1/index.mdx
content/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.2/index.mdx
content/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
content/messaging/agent-chat-api/v3.4/index.mdx
content/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-9080-require_every_value)
- [Jira](https://livechatinc.atlassian.net/browse/API-9080)

API-9080 Add require_every_value to list_archives and reports filters

---

content/extending-chat-widget/custom-identity-provider/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/fix-custom-identity-provider-docs-code)
- [Jira](https://livechatinc.atlassian.net/browse/XXX-XXX) n/a
[Customer reported](https://livechat.slack.com/archives/C0BFQK3J9/p1627288691294500) a problem with docs of Custom Identity Provider. There is an ambiguous property `pendingTokenRequest` which in fact should just be `tokenPromise`.

Fix Custom Identity Provider docs code

---

src/pages/management/changelog/publish-todo.md
src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Feature branch](https://developers.labs.livechat.com/docs/feature/API-9171-simplify-chat-scopes)
- [Jira](https://livechatinc.atlassian.net/browse/API-9171)

API-9171 Simplify chat scopes

---

.gitignore
_redirects
package-lock.json
src/pages/management/limits/index.mdx

Instead of removing the content from https://developers.livechat.com/docs/management/limits, we'll add a temp redirect to the LiveChat pricing page.

(NO-DPS) Add 302 redirect for Limits

---

src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-9184)

Update default behaviour of some agen-api methods.

---

src/utils/index.js

- [Jira](https://livechatinc.atlassian.net/browse/DPS-2867)
Related to: https://github.com/algolia/docsearch-configs/pull/4443

(DPS-2867) Extend search results

---

src/components/extensions/Headings.js

Check if external image

---

src/pages/extending-agent-app/design-system/index.mdx

Quick fix for broken Design System links in docs

[no-dps] Fix links to Design System page

---

src/components/Page/index.js

(NO-DPS) Bug fix - adjusted links scrolling flow to SSR

---

payloads/data-reporting/v3.4/reports-api/filters.json

Fix event_types filter example

Fix event_types filter example

---

src/pages/messaging/index.mdx

(NO-DPS) Bug fix - broken video 

---

payloads/data-reporting/v3.4/reports-api/index.js
payloads/data-reporting/v3.4/reports-api/responses/chats/engagement.json
src/pages/data-reporting/changelog/index.mdx
src/pages/data-reporting/reports-api/v3.4/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-9691)
New report in reports-api - chat engagement

add chat engagement report description

---

src/pages/authorization/sign-in-with-livechat/index.mdx

Bug fix - broken width of account image

---

src/pages/extending-chat-widget/chat-widget-moments/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-2678)
Fix direct chat link - use the new version

use new direct chat link URL

---

src/pages/messaging/agent-chat-api/index.mdx

Fix table rendering in Agent API

---

src/components/Page/index.js

(NO-DPS) Disable LCS promotion

---

src/pages/extending-chat-widget/chat-widget-moments/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-2658)
A little catch-up with recent changes in moments-sdk:
Sometime ago we added `isFragile` property and `setIsFragile` method allowing for its modification.
We also started using `LauncherData` properties consisting of `licenseId` and `chatId`
It should be merged after:  https://github.com/livechat/moments-sdk/pull/27 and publication of the moments packages.

[CW-2658] Describe LauncherData and add missing isFragile property handling in moments-sdk

---

src/configs/articles.json
src/configs/categories.json
src/pages/authorization/authorization-in-practice/index.mdx
src/pages/authorization/authorizing-api-calls/index.mdx
src/pages/authorization/index.mdx
src/pages/authorization/scopes/index.mdx
src/pages/getting-started/livechat-apps/webhook-apps/index.mdx

- Describe **Chat webhooks** as a way to configure webhooks, in **Building webhooks app doc**
- Specify that one cannot get a customer token using PATs
- Remove categories in the Authorization section to remove duplicate document titles

Misc fixes

---

scripts/version.js

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3363)
- Update paths in the new docs structure (old: `/content/`, new: `/src/pages/`)
- Improve message copy
- Add support for new versioned documents 👇
**Agent Chat API:** [RTM pushes](https://developers.livechat.com/docs/messaging/agent-chat-api/rtm-pushes), [Data structures](https://developers.livechat.com/docs/messaging/agent-chat-api/data-structures)
**Customer Chat API:** [RTM pushes](https://developers.livechat.com/docs/messaging/customer-chat-api/rtm-pushes), [Data structures](https://developers.livechat.com/docs/messaging/customer-chat-api/data-structures)
**Management:** [Webhooks](https://developers.livechat.com/docs/management/webhooks)

(DPS-3363) Fix migration scripts

---

src/configs/articles.json
src/pages/messaging/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3091)
Small refactor of the **Rules and **Conditions** section in the docs.

[DPS-3091] Refactor of the Messaging > Rules and Conditions

---

src/components/core/SideNav/SideNav.js
src/utils/index.js

(NO-DPS) Bug fix - customer SDK isn't displayed on sidebar 

---

src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.1/index.mdx
src/pages/messaging/agent-chat-api/v3.1/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/index.mdx
src/pages/messaging/customer-chat-api/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.1/index.mdx
src/pages/messaging/customer-chat-api/v3.1/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.4/index.mdx
src/pages/messaging/customer-chat-api/v3.4/rtm-reference/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-10036)

Update 'update_customer' description.

---

src/components/Page/index.js
src/components/core/components.js
src/components/core/redoc.css
src/components/core/version.js
src/configs/articles.json
src/configs/articlesVersions.json
src/configs/redoc/configs.js
src/configs/redoc/customer-accounts-api/config.js
src/configs/redoc/global-accounts-api/config.js
src/constant/index.js
src/pages/authorization/customer-accounts-api/index.mdx
src/pages/authorization/customer-accounts-api/v1.0/index.mdx
src/pages/authorization/customer-accounts-api/v2.0/index.mdx
src/utils/index.js

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3203)
Add support for versions inside redoc docs.

(DPS-3203) Customer SSO versioning

---

src/pages/data-reporting/reports-api/v2.0/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3415)

(DPS-3415) Table is too narrow

---

src/components/core/components.js
src/components/extensions/CodeBlocks.js

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3412)

(DPS-3412) Bug fix - Fix CSS for method names

---

src/pages/data-reporting/reports-api/v3.4/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-9701)

API-9701 Fix reports links

---

payloads/management/v3.3/configuration-api/responses/properties/listProperties.json
payloads/management/v3.4/configuration-api/responses/properties/listProperties.json

Added missing key to the payload including the public access key.

(NO-DPS) Add public key to the list properties payload

---

src/components/core/SideNav/MenuItem.js

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3399)

(DPS-3399) The highlighted space around an item in sidebar isn't clickable

---

src/components/extensions/Placeholder.js
src/pages/authorization/index.mdx
src/pages/data-reporting/reports-api/v2.0/index.mdx
src/pages/extending-agent-app/index.mdx
src/pages/management/index.mdx
src/pages/messaging/customer-chat-api/index.mdx
src/pages/messaging/customer-chat-api/v3.1/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.4/index.mdx

- Fixed formatting of sample requests in Reports API v2.0
- Fixed a couple links
- Added margin under images

Fix links, formatting in Reports API, and more

---

src/pages/authorization/authorizing-api-calls/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-10140)

API-10140: remove info about reports-api not supporting PATs

---

src/pages/messaging/agent-chat-api/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-pushes/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-10087)

Fix pos of transferred_from within incoming_chat push.

---

scripts/buildArticles.js
src/components/core/SideNav/ContentSideNav.js
src/components/core/components.js
src/components/core/layout.css
src/configs/articles.json

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3416)

(DPS-3416) Right-side sidebar is missing method names & script refactor

---

.gitignore
package-lock.json
package.json

Because of memory limits on netlify, temporarly we have to switch to manaul deploys. More info talk to @ale-kacperczyk @jakubsikora .

Switch to manual deployment

---

src/pages/messaging/customer-chat-api/v3.4/rtm-pushes/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-9400)

API-9400 Add access_token_revoked reason for customer_disconnected push

---

_redirects
src/pages/messaging/apple-business-chat/index.mdx
src/pages/messaging/apple-messages-for-business/index.mdx

Preview: https://61e57a85f219519455f2cd98--livechat-public-docs.netlify.app
- [Jira](https://livechatinc.atlassian.net/browse/AA-12453)
Added a description of new quick-replies endpoint for Apple Business Chat. I've also changed the name Apple Business Chat to Apple Messages for Business according to the Apple request

AA-12453: ABC: Add support for Quick Replies

---

.github/CODEOWNERS

Added CODEOWNERS file to protect `master`. We will require approval from a member of @livechat/tech-content  when any file in `payload` or `pages` is changed

Setup code ownership rules

---

.github/CODEOWNERS
.github/pull_request_template.md

- I removed Jakub and Artur from code owners because they don't need to be modified for most cases.
- I updated the pull request template.

Modified codeowners and pull request template

---

src/configs/articles.json
src/pages/getting-started/app-guides/index.mdx
src/pages/getting-started/livechat-apps/index.mdx
src/pages/monetization/how-to-monetize-apps/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/DPS-3317)
Preview: https://61e965d263ed201413188ef4--livechat-public-docs.netlify.app/

(DPS-3317) Embed video tutorials in docs

---

src/pages/extending-chat-widget/chat-widget-moments/index.mdx

Bump Moments SDK UMD build version in script tag version usage description.

Bump Moments SDK UMD build version

---

src/pages/data-reporting/reports-api/index.mdx
src/pages/data-reporting/reports-api/v3.5/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-9701)

API-9701 Move chats response times reports to chats section

---

payloads/data-reporting/v3.4/reports-api/responses/chats/engagement.json
payloads/data-reporting/v3.5/reports-api/responses/chats/engagement.json
src/pages/data-reporting/reports-api/index.mdx
src/pages/data-reporting/reports-api/v3.5/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-9691)

API-9691 Fix chats engagement report response payload

---

src/pages/extending-chat-widget/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/DED-66)
- [Preview](https://6218ddf5aab5c9dc6e9a0869--livechat-public-docs.netlify.app/extending-chat-widget)
Added a subsection for Chat Widget Adapters in the Extending Chat Widget section.

Mention Adapters in Overview

---

src/pages/management/changelog/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-8859)

Align with PAT changes in v3.5

---

src/configs/articles.json
src/pages/messaging/apple-messages-for-business/index.mdx

Preview: https://622b178ceada530060743265--livechat-public-docs.netlify.app
As requested on Slack.

Rename ABC to Apple Messages

---

src/pages/messaging/customer-chat-api/changelog/index.mdx
src/pages/messaging/customer-chat-api/v3.5/rtm-pushes/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-10281)

New dc reason in customer_disconnected push.

---

src/configs/articles.json
src/constant/index.js
src/pages/authorization/scopes/index.mdx

https://623344053bdbf513d10d9a6f--livechat-public-docs.netlify.app/
- [Jira](https://livechatinc.atlassian.net/browse/ACC-1156)

(ACC-1156) New product scopes

---

src/configs/articles.json
src/pages/extending-agent-app/product-cards/index.mdx

https://62346e2186bc521eeb721f89--livechat-public-docs.netlify.app
- [Jira](https://livechatinc.atlassian.net/browse/DED-41)

(DED-41) Sample app for Product Cards 

---

src/configs/articles.json
src/pages/authorization/authorizing-api-calls/index.mdx
src/pages/management/index.mdx
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.3/index.mdx
src/pages/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.5/index.mdx
src/pages/messaging/agent-chat-api/v3.5/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/index.mdx
src/pages/messaging/customer-chat-api/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.3/index.mdx
src/pages/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.5/index.mdx
src/pages/messaging/customer-chat-api/v3.5/rtm-reference/index.mdx

https://62445bd84c690000bc8723b2--livechat-public-docs.netlify.app/
- Method links in Agent Chat API and Customer Chat API
- Annotation to `redirect_uri` in customer auth
- Annotation to Add User to Chat and adding more than 1 agent to chat

(NO-DED) Misc fixes 03-2022

---

.gitignore
package.json

(DED-37) Add generated by build jsons to gitignore

---

src/pages/authorization/authorizing-api-calls/index.mdx
src/pages/extending-chat-widget/rich-messages/index.mdx

(NO-DED)small typo fixes

---

src/pages/monetization/app-review-process/index.mdx

(DED124) adding copy guidelines to the Monetization document, under: App Review process

---

src/pages/management/webhooks/index.mdx

DED-130 fixing link so it leads to the correct place

---

src/pages/authorization/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/DED-133)
Added the Auth video to the Authorization section in docs. I created a new section as I decided that when over time there'll be more videos, we can add them under the same "Video explainers" category.

[DED-133] Embed the Authorization video in docs

---

src/components/extensions/CodeBlocks.js

- [Jira](https://livechatinc.atlassian.net/browse/DED-122)

(DED-122) Decrease top padding value in Code components

---

src/configs/articles.json
src/constant/index.js
src/pages/authorization/scopes/index.mdx
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

https://624fed6409614e49456c137d--livechat-public-docs.netlify.app
- [Jira](https://livechatinc.atlassian.net/browse/API-10179)
New scopes:
- `properties.license.value--my.rw`
- `properties.license.value--all.rw`
- `properties.group.value--my.rw`
- `properties.group.value--all.rw`
More details about accessing the methods `list/update/delete_license/group_properties`.

API-10179: make public license/groups properties more secure

---

src/pages/getting-started/livechat-apps/index.mdx
src/pages/messaging/agent-chat-api/index.mdx

Fixed link in the LiveChat Apps guide and fixed incorrect info about remove-user-from-chat possible values (reported on docs channel).

[NO-DED] fix link and change info about possible value in remove-user method

---

.github/pull_request_template.md

- [Jira](https://livechatinc.atlassian.net/browse/DED-141)
Updates the PR template

(DED-141) Edit PR template

---

payloads/data-reporting/v3.5/reports-api/index.js
payloads/data-reporting/v3.5/reports-api/responses/tags/chatUsage.json
payloads/management/v3.5/configuration-api/index.js
payloads/management/v3.5/configuration-api/responses/tags/listTags.json
src/constant/index.js
src/pages/authorization/scopes/index.mdx
src/pages/data-reporting/changelog/index.mdx
src/pages/data-reporting/reports-api/v3.5/index.mdx
src/pages/management/changelog/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx
src/pages/management/webhooks/v3.5/index.mdx
src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.5/rtm-pushes/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-10298)

Describe v3.5 tags.

---

src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.3/index.mdx
src/pages/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.5/index.mdx
src/pages/messaging/agent-chat-api/v3.5/rtm-reference/index.mdx

DED-138 Tag thread and untag thread descriptions added

---

src/constant/index.js
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v2.0/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.3/index.mdx
src/pages/messaging/agent-chat-api/v3.5/index.mdx
src/pages/messaging/customer-chat-api/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.3/index.mdx
src/pages/messaging/customer-chat-api/v3.5/index.mdx

Responding to the [issue from Slack.](https://livechat.slack.com/archives/C2XMTMQ5S/p1649842035371799)

Link wrong_region error in data centers section

---

payloads/messaging/v3.2/agent-chat-api/other-structures/chat.json
payloads/messaging/v3.3/agent-chat-api/other-structures/chat.json
payloads/messaging/v3.4/agent-chat-api/other-structures/chat.json
payloads/messaging/v3.5/agent-chat-api/other-structures/chat.json

DED-143 adding tags array to the chat structure

---

.github/workflows/links.yml

(DED-146) Run Link Checker once a month - config update

---

.lycheeignore

[NO-DED] Remove entry from lycheeignore file

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.3/index.mdx
src/pages/messaging/agent-chat-api/v3.5/index.mdx

feature/DED-71 adding delete, get bot and mark events as seen methods descriptions

---

src/pages/extending-chat-widget/customer-sdk/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-2907)
Add Customer SDK connect method example for both described variants:
- SDK being initialized with `autoConnect: false`
- SDK being disconnected with `inactivity_timeout` reason

(CW-2907) CustomerSDK connect method example

---

src/constant/index.js
src/pages/authorization/scopes/index.mdx
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

NO-DED changing dots for colons in properties scopes

---

src/constant/index.js
src/pages/getting-started/app-guides/properties/index.mdx
src/pages/messaging/customer-chat-api/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.3/index.mdx
src/pages/messaging/customer-chat-api/v3.5/index.mdx

NO-DED correcting typo mistakes in docs

---

src/configs/redoc/customer-accounts-api/specv2.yml

NO-DED changing name in tokens authentication

---

src/pages/getting-started/app-guides/agent-app-widgets/index.mdx
src/pages/getting-started/app-guides/chat-actions/index.mdx
src/pages/getting-started/app-guides/chat-webhooks/index.mdx
src/pages/getting-started/app-guides/in-app-upgrades/index.mdx
src/pages/getting-started/livechat-apps/index.mdx

There was no ticket.
Fixed some typos I have found in Getting Started section.

Fixed typos in Getting Started

---

src/pages/management/index.mdx

There was no ticket.
Fixed some typos I have found in Management Overview section.

Fixed typos in Management Overview

---

src/configs/redoc/global-accounts-api/spec.yml

NO-DED updating yml in livechat-public-docs

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

NO-DED adding required parameter to Unregister Webhook method

---

src/pages/default-credentials.md

DED-221 creating default credentials file

---

src/pages/index.mdx

(NO-DED) Add missing comma

---

.github/workflows/deploy.yml
src/pages/index.mdx

(NO-DED) Fix deploy GA

---

src/pages/extending-chat-widget/custom-identity-provider/index.mdx

[Link your Jira ticket.](https://livechatinc.atlassian.net/browse/DED-222)
- [Jira]()
I was supposed to link the tutorial to docs around the time when we publish that tiny correction to the tutorial's title on Platform Updates (PR reader to publish, send you the link on Slack) :)

NO-DED linking Custom Identity Provider tutorial to docs

---

src/pages/authorization/authorizing-api-calls/index.mdx

DED-219 adding Postman button with Authorization collection

---

src/pages/authorization/authorizing-api-calls/index.mdx

NO-DED adding button to Postman with customer auth collection

---

src/pages/management/webhooks/index.mdx
src/pages/management/webhooks/v3.3/index.mdx
src/pages/management/webhooks/v3.5/index.mdx
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.5/index.mdx
src/pages/messaging/agent-chat-api/v3.5/rtm-reference/index.mdx

DED-224 adding scopes descriptions to methods in v3.4 WEB and RTM

---

src/contexts/auth.js

Avatar hotfix

---

src/pages/extending-chat-widget/chat-widget-adapters/angular-adapter/index.mdx
src/pages/extending-chat-widget/chat-widget-adapters/react-adapter/index.mdx
src/pages/extending-chat-widget/chat-widget-adapters/vue-adapter/index.mdx

Followup to changes made here https://github.com/livechat/chat-widget-adapters/pull/49
Preview: https://fix-cw-redundant-visibility-prop--livechat-public-docs.netlify.app
Remove redundant visibility prop description form packages README.

Fix: widget adapters redundant visibility prop

---

src/configs/redoc/global-accounts-api/spec.yml
src/pages/authorization/authorizing-api-calls/index.mdx

- [Jira]()
Two different issues reported on `platform-docs` are fixed here

NO-DED corrections reported on platform docs

---

.husky/pre-commit
package-lock.json
package.json

N/A
N/A
- Configure [husky](https://npmjs.com/package/husky) for automatic git-hook registration
- Add pre-commit git hook for branch name length checking using shell script

Add pre-commit hook for branch name length checking

---

src/components/core/Profile/Profile.js

(NO-DED) Add login attempt to Amplitude tracking

---

payloads/management/v3.5/configuration-api/index.js
payloads/management/v3.5/configuration-api/responses/other/getProductSource.json
src/pages/management/changelog/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-11041)
A new endpoint in configuration-api (v3.5) to retrieve the "source" parameters used when activating the LiveChat product.

API-11041 added docs for new endpoint in conf-api: get_product_source

---

src/pages/getting-started/app-guides/properties/index.mdx
src/pages/messaging/customer-chat-api/index.mdx
src/pages/messaging/customer-chat-api/v3.3/index.mdx
src/pages/messaging/customer-chat-api/v3.5/index.mdx

- [Jira]()
Dear reviewers, I have included two different cases reported on the #platform-docs. That is why I mark each case with a comment mentioning you, so you are not surprised and sure what to check :)

NO-DED fixing issues from platform-docs

---

src/pages/authorization/index.mdx

DED-258 adding sample apps links to auth documentation

---

.env.development
.env.production
src/components/core/Profile/Profile.js

- [Jira](https://livechatinc.atlassian.net/browse/DED-268)
Add a link to Discord in the dropdown.

(DED-268) Link to Discord in dropdown

---

src/pages/authorization/sign-in-with-livechat/index.mdx

DED-276 linking sample apps in Sign in with LiveChat

---

src/styles/algolia.css
src/utils/index.js

(DED-297) Docsearch improvements 

---

.github/workflows/deploy.yml

(NO-DED) update node version on deploy GitHub Action

---

src/pages/messaging/agent-chat-api/v3.5/rtm-pushes/index.mdx

API-11353 added info about groups_status_updated push

---

payloads/management/v3.5/configuration-api/responses/agents/listAgents.json
src/pages/management/changelog/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

[Jira](https://livechatinc.atlassian.net/browse/API-11306)

API-11306 new additional agent field last_logout

---

src/pages/management/changelog/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

API-10943 added list_groups_properties

---

src/pages/authorization/authorizing-api-calls/index.mdx
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/v3.5/index.mdx

NO-DED fixing issues reported by Orzech and Aleksander on #platform-docs in Oct

---

src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.3/index.mdx
src/pages/messaging/agent-chat-api/v3.5/index.mdx

NO-DED solving the issue with the get customer method reported on platform docs

---

src/components/core/Footer/Footer.js
src/pages/authorization/global-accounts/index.mdx
src/pages/extending-chat-widget/rich-messages/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

NO-DED correcting typo and links reported on platform docs

---

src/styles/redoc.css

- [Jira](https://livechatinc.atlassian.net/browse/DED-375)

(DED-375) Missing title in the document

---

src/pages/management/changelog/index.mdx
src/pages/management/configuration-api/v3.5/index.mdx

Jira: https://livechatinc.atlassian.net/browse/API-11629

API-11629 Bot-related batch methods documentation

---

src/pages/management/changelog/index.mdx

Fixed typo in management changelog

---

src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

Jira: https://livechatinc.atlassian.net/browse/API-11763

API-11763 Removed List Customers method from Agent Chat API

---

src/pages/getting-started/helpdesk-apps/index.mdx

- [Jira]()
For now, added `available soon` descriptions in 2 places in the Building HD apps tutorial

NO-DED adding available soon tag to the hd building apps tutorial

---

src/styles/prism.css

- [Jira](https://livechatinc.atlassian.net/browse/DED-379)

(DED-379) Line of code does not divide itself in docs and enters sidebar

---

src/styles/prism.css

- [Jira]()
Fix white space wrapping in code blocks.

(NO-DED) Fix white space wrapping in code blocks

---

src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.6/data-structures/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-10913)
Extend agent's Thread object with `customer_visit` field.

API-10913: Extend agent's Thread with customer_visit

---

src/pages/monetization/billing-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-12062)
We are introducing a new API version in billing-api, but since the billing documentation is not very robust, for now we simply want to update the URLs used in the docs (and fix some sample responses while at it).

API-12062 updated urls and payloads for billing api

---

src/contexts/auth.js

- [Jira](https://livechatinc.atlassian.net/browse/DED-326)

(DED-326) Fix errors handling

---

src/components/core/Rating/ThumbIcon.js
src/components/core/Rating/index.js
src/utils/analytics.js

- [Jira](https://livechatinc.atlassian.net/browse/DED-395)
[DED-395]: https://livechatinc.atlassian.net/browse/DED-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(DED-395) Add Piwik to the rating component

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

- [Jira]()
Correcting requests in the Create Agent methods (v3.5 & v3.6)
PREVIEW - https://63c651e83e20687ba4116195--livechat-public-docs.netlify.app

NO-DED correcting create agent request v3.5

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

- [Jira]()
PREVIEW - https://63c7aaf4d289a5578cb3240e--livechat-public-docs.netlify.app/management/configuration-api/v3.6#check-product-limits-for-plan

NO-DED fixing 2 methods in Conf API v3.5 & v3.6

---

src/components/Page/index.js
src/components/core/Profile/Profile.js
src/components/core/SideNav/ContentSideNav.js
src/components/core/SideNav/SideNav.js
src/components/core/header.js
src/styles/layout.css
src/styles/redoc.css

- [Jira](https://livechatinc.atlassian.net/browse/DED-431)

(DED-431) Promo banner in docs

---

src/styles/layout.css

(DED-431) Banner hotfix

---

src/configs/redoc/customer-accounts-api/specv2.yml
src/pages/authorization/customer-authorization/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-12034)
Nothing were changed on API side. This is just more precise description of `v2/customer/token` endpoint requirements.
PREVIEW - https://63ca78a58e7c2c07b22adbf9--livechat-public-docs.netlify.app/authorization/customer-authorization#case-new-customer

API-12034 Updated description of redirect_uri

---

src/constant/index.js
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

reported on slack: https://text.slack.com/archives/C2FAU97K2/p1674053411944719 
Fix for invalid links to webhook descriptions
PREVIEW - https://63ca6abae6cb73777ccc2ece--livechat-public-docs.netlify.app

Fix webhook description links

---

src/pages/index.mdx
src/pages/messaging/index.mdx

fixed small typos in the documentation

fixed typo on the message documentation page

---

src/constant/index.js
src/pages/data-reporting/reports-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/DED-495?atlOrigin=eyJpIjoiYzViM2Q4ZjNhYzdhNDk4NGFmYTdlYzczZGU3ZmRmNjQiLCJwIjoiaiJ9)
Preview - https://63ce907b09733425bf5fc34c--livechat-public-docs.netlify.app

NO-DED changing v3.2 for deprecated

---

src/components/core/header.js
src/components/core/version.js

- [Jira](https://livechatinc.atlassian.net/browse/DED-497)
We no longer track the following events logged from the documentation:
- Version selected
- Top menu tab clicked
- External link clicked

(DED-497) Remove untracked amplitude events

---

_redirects

https://63d3b121e523157f573cc1d1--livechat-public-docs.netlify.app/getting-started/app-guides/onboarding
- [Jira]()
I had a problem here with checking if it actually works. The redirects don't work on our previews. I thought to check it on Labs, but I have not found anything linking to the Onboarding BB in the docs.

NO-DED correcting redirect to the Onboarding BB

---

src/components/core/version.js

https://63db999b867438377bbfdec6--livechat-public-docs.netlify.app/
Added the date of decommissioning in the version bar for v3.2

(NO-DED) Decommission date for v3.2 in the version bar

---

src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

- [Jira]()
PREVIEW - https://63d11b2b1311ba179d8837cc--livechat-public-docs.netlify.app/messaging/agent-chat-api/rtm-reference#request-29

API-11913 add highest_available

---

src/pages/getting-started/helpdesk-apps/index.mdx

https://63e200ffdca38b2d446ada03--livechat-public-docs.netlify.app
- [Jira]()

NO-DED available_soon tag step 5 in hd apps guide removed

---

src/components/core/Rating/modal.js

- [Deploy Preview](https://63e26b4ef22033005002fafd--livechat-public-docs.netlify.app/)
- [Jira](https://livechatinc.atlassian.net/browse/DED-498)
- Add prefilled URL to GoogleForms feedback modal field

(DED-498) Add prefilled URL to GoogleForms feedback modal field

---

src/pages/extending-agent-app/products-sdk/agent-app-sdk/index.mdx

https://63ea092dc36db74936c14b71--livechat-public-docs.netlify.app
- [Jira]()

[NO-DED] Update links to sample apps

---

src/pages/management/configuration-api/v2.0/index.mdx

https://63eba54f12738a12e816a6f2--livechat-public-docs.netlify.app/management/configuration-api/v2.0#agents-deprecated
- [Jira](https://livechatinc.atlassian.net/browse/DED-524?atlOrigin=eyJpIjoiZjFiZjRkZDBlYmJkNGY0ODk1MmM4MzhmM2MwZjBjNTQiLCJwIjoiaiJ9)
Links added. I have done it the way some methods were already described in this document (put info in the yellow box). Please check if the links added are the correct ones.

NO-DED Linking new versions of the methods in Conf v2

---

src/pages/management/changelog/index.mdx
src/pages/management/webhooks/index.mdx
src/pages/management/webhooks/v3.6/index.mdx

https://63ea0655fb18ad4c965c4bbd--livechat-public-docs.netlify.app
- [Jira](https://livechatinc.atlassian.net/browse/API-12158)
Update changelog and example configuration webhooks body with `requester` property.

API-12158 Added requester property in configuration webhooks v3.6

---

src/components/Page/index.js
src/components/core/Profile/Profile.js
src/components/core/SideNav/ContentSideNav.js
src/components/core/SideNav/SideNav.js
src/components/core/header.js
src/styles/layout.css
src/styles/redoc.css

- [Jira](https://livechatinc.atlassian.net/browse/DED-531)

(DED-531) Hide the promo banner in docs

---

src/constant/index.js
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v2.0/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

https://63f6029cb1318a7af9c98915--livechat-public-docs.netlify.app/management/configuration-api/v2.0
- [Jira]()

DED-533 tagging v2 Conf as deprecated and hiding it

---

netlify.toml
package.json
scripts/redoc.js

Enable automatic deploys and dev previews 

---

src/pages/extending-agent-app/index.mdx
src/pages/extending-agent-app/products-sdk/agent-app-sdk/index.mdx

DED-520 Updating link to the Supervisor App

---

src/utils/index.js

- [Jira](https://livechatinc.atlassian.net/browse/DED-522)
Display missing info about which API search result is related to.

(DED-522) Display missing info about which API the result is related to

---

src/api/accounts.js
src/api/livechat.js
src/contexts/auth.js

(DED-550) Migrate to the newest version of Configuration API

---

src/pages/getting-started/index.mdx
src/pages/getting-started/installing-livechat/android-widget/index.mdx
src/pages/monetization/billing-api/index.mdx

[no-ded] Misc fixes

---

src/constant/index.js
src/utils/index.js

- [Jira](https://livechatinc.atlassian.net/browse/DED-240)
- Filter search results to not show hidden pages

(DED-240) Filter search results

---

src/components/SecondGrader/index.js

Disable AI Assist by default to see how many users will turn it on.

Disable AI Assist by default

---

src/pages/authorization/authorizing-api-calls/index.mdx
src/pages/getting-started/app-guides/app-monetization/index.mdx
src/pages/getting-started/app-guides/index.mdx
src/pages/getting-started/helpdesk-apps/index.mdx
src/pages/monetization/app-review-process/index.mdx
src/pages/monetization/billing-api/index.mdx

- [Jira]()
Linked/adjusted HD marketplace in places that needed it. Also, changed the description in one document.

DED-450 Linking HD Marketplace

---

src/components/core/version.js
src/constant/index.js
src/pages/data-reporting/reports-api/v3.2/index.mdx
src/pages/extending-agent-app/products-sdk/agent-app-sdk/index.mdx
src/pages/extending-chat-widget/rich-messages/index.mdx
src/pages/getting-started/app-guides/chat-webhooks/index.mdx
src/pages/getting-started/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.2/data-structures/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.2/data-structures/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-pushes/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx

- [Jira]()
As agreed, documents presenting v3.2 has been hidden. I also removed mentions about v3.2 that I found in the docs. I decided to remove info about v3.2 in PUs when the version is completely decommissioned, as there might be still people who will need them.

DED-594 v3.2 documents to be hidden

---

src/pages/extending-chat-widget/customer-sdk/index.mdx
src/pages/extending-chat-widget/customer-sdk/v1.0/index.mdx
src/pages/extending-chat-widget/customer-sdk/v2.0/index.mdx

- [Jira]()
React-native in the customer-auth library as part of the react-native widget project was supported in the past, although it is no longer developed. That is why the info about it needs to be removed. The case reported on [#platform-docs](https://text.slack.com/archives/C2XMTMQ5S/p1680772416731159) and deleting this part from the docs has been confirmed with Konrad Kruk.  I have hidden the info, not deleted it, as we may be describing it in the future when the case will be taken care of. 
Apply changes and resolve conflicts. Once the described functionality lands on prod, let us know on #platform-docs-releases that your PR is ready for release. We will **merge** and …

NO-DED Removing using the API in React Native

---

src/configs/containers.json
src/pages/apis-and-sdks/index.mdx

- [Jira]()
I have created a new index.mdx file and added a new section into the `containers.json`. I was unsure if adding this new section to the `categories.json` is also necessary, and if yes, when is it supposed to be done? When a new navbar is published?🤔 @arturfracala, please let me know when I can publish these changes so your work with the new navbar is not disturbed.

DED-596 Create a new page in docs listing all our APIs and SDKs

---

src/constant/index.js

Fixed typo in scope description

Fixed typo in scope description

---

src/pages/authorization/agent-authorization/index.mdx
src/pages/authorization/authorization-in-practice/index.mdx
src/pages/authorization/customer-authorization/index.mdx
src/pages/authorization/faq/index.mdx
src/pages/extending-agent-app/products-sdk/agent-app-sdk/index.mdx
src/pages/extending-agent-app/products-sdk/helpdesk-sdk/index.mdx
src/pages/extending-chat-widget/chat-widget-adapters/angular-adapter/index.mdx
src/pages/extending-chat-widget/chat-widget-adapters/react-adapter/index.mdx
src/pages/extending-chat-widget/chat-widget-adapters/vue-adapter/index.mdx
src/pages/extending-chat-widget/chat-widget-moments/index.mdx
src/pages/extending-chat-widget/custom-identity-provider/index.mdx
src/pages/extending-chat-widget/javascript-api/index.mdx
src/pages/extending-chat-widget/javascript-api/v2.0/index.mdx
src/pages/getting-started/installing-livechat/android-widget/index.mdx
src/pages/getting-started/installing-livechat/index.mdx
src/pages/getting-started/installing-livechat/ios-widget/index.mdx
src/pages/messaging/chat-sdk/index.mdx

- [Jira]()
This is all I managed to do :)

DED-218 adding copy to clipboard to CodeBlocks

---

src/pages/monetization/partner-program-api/index.mdx

Update docs for Partner Program API:
```
GET /v2/partners/affiliates/metrics/trials
GET /v2/partners/affiliates/metrics/earnings
GET /v2/partners/affiliates/metrics/conversions
GET /v2/partners/affiliates/metrics/clicks
```

Pp 8330/update docs metrics endpoints

---

src/pages/monetization/partner-program-api/index.mdx

[Link your Jira ticket.
](https://livechatinc.atlassian.net/browse/PP-8424)
- [Jira]()
Extending PP docs with Affiliate links' endpoints

PP-8422: Get Affiliate Links documented

---

package-lock.json
package.json
src/components/core/Profile/Profile.js
src/components/extensions/CopyToClipboardIcon.js
src/hooks/useRating.js
src/pages/_app.js
src/utils/index.js

(DED-523) Log user email to Amplitude from docs

---

src/components/core/icons.js
src/components/core/version.js
src/utils/index.js

- [Jira](https://livechatinc.atlassian.net/browse/DED-95)
- implementation of version component new design 

(DED-95) Version component - new design

---

src/components/core/icons.js
src/components/core/version.js
src/utils/index.js

- [Jira]()
- Revert to previous version color scheme

(NO-DED) Revert to previous version color scheme

---

_redirects
src/constant/header.js
src/pages/extending-agent-app/design-system/index.mdx
src/pages/monetization/app-review-process/index.mdx

DED-610 Change links to Design System

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-8569)

PP-8569: archive campaign

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-8329)

PP-8564: get partner profile

---

src/constant/header.js
src/pages/authorization/index.mdx
src/pages/data-reporting/reports-api/v2.0/index.mdx
src/pages/extending-agent-app/products-sdk/helpdesk-sdk/index.mdx
src/pages/extending-chat-widget/custom-identity-provider/index.mdx
src/pages/getting-started/app-guides/chat-actions/index.mdx
src/pages/getting-started/app-guides/chat-webhooks/index.mdx
src/pages/getting-started/app-guides/properties/index.mdx
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx
src/pages/management/index.mdx
src/pages/management/webhooks/index.mdx
src/pages/management/webhooks/v3.2/index.mdx
src/pages/management/webhooks/v3.3/index.mdx
src/pages/management/webhooks/v3.4/index.mdx
src/pages/management/webhooks/v3.6/index.mdx
src/pages/monetization/how-to-monetize-apps/index.mdx

Hotfix - platform updates links 

---

src/components/core/Search/index.js

Fix search 

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-8576)

PP-8600: Livechat switched to product

---

src/styles/redoc.css

(DED-650) Tweak styling of Redoc pages

---

src/pages/getting-started/app-guides/integrations/index.mdx
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

- [Jira]()
As agreed missing scope was added together with its description

NO-DED Adding one required scope to the Create Agent method

---

src/pages/management/configuration-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.3/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-pushes/index.mdx

NO-DED Fixing links in incoming_customers & register webhooks

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

DED-659 Standardise the references in methods in Conf API 

---

src/styles/algolia.css

- [Jira](https://livechatinc.atlassian.net/browse/DED-630)
- change z-index of docsearch container

(DED-630) Change z-index of docsearch container

---

src/configs/containers.json

- [Jira](https://livechatinc.atlassian.net/browse/DED-631)
- add missing trailing slash to extending-agent-app slugs

(DED-631) Add missing trailing slash to extending-agent-app slugs

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-12939)
Clarify when to use Enable/Disable License Webhooks.

API-12939: Clarify when to use enable/disable license webhooks

---

src/pages/getting-started/app-guides/integrations/index.mdx

NO-DED Adding video link to the Integrating GitHub repo to your app document

---

src/pages/management/configuration-api/v2.0/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-12815)
New greeting trigger `ads_traffic`

API-12935 Added ads_traffic greeting description

---

src/pages/management/webhooks/index.mdx
src/pages/management/webhooks/v3.3/index.mdx
src/pages/management/webhooks/v3.4/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-12906)
In <=v3.5 it's queued_at_us.

API-12906: fix queued_at field name

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-8798)

PP-8800: get solution licenses by status

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-8914)

PP-8943: adjust GET /v2/partners/solutions/licenses endpoint

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-8966)

PP-8966: Updated "update billing" with state prop

---

src/pages/monetization/partner-program-api/index.mdx

Pp 9033/update docs

---

src/pages/extending-chat-widget/javascript-api/index.mdx
src/pages/extending-chat-widget/javascript-api/v2.0/index.mdx
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

(NO-DPS) Fixes #160823

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-9092)

Pp 9092/document endpoint

---

src/pages/extending-agent-app/design-system/index.mdx

[NO-DPS] Fix Design System links

---

src/pages/extending-agent-app/design-system/index.mdx
src/pages/monetization/app-review-process/index.mdx

[NO-DPS] Fix misc links

---

package-lock.json
package.json
src/pages/_app.js

Add store metrics

---

src/pages/monetization/billing-api/index.mdx

Updates in Billing API

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-9097)

PP-9097 solution license report

---

src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-pushes/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/LC-134) – this was renumbered at some point, so branch's name starts with AA-

LC-134 add new disconnected reason

---

src/constants/index.js
src/pages/extending-chat-widget/customer-sdk/v3.0/index.mdx
src/pages/extending-chat-widget/javascript-api/v3.0/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-3379)
Adding docs for upcoming customer-sdk@4.0.0 release

[CW-3379] Widget customer-sdk 4.0.0

---

src/configs/redoc/global-accounts-api/spec.yml

Account organization settings docs

---

src/pages/monetization/billing-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/MP-1442)
- Added description for a new field in recurrent charges, `external_id`
- Described multi-product support
- Renamed "LiveChat Billing API" to "Text Billing API"
- Other small updates

Refreshed billing docs

---

src/configs/containers.json
src/pages/data-reporting/app-monitoring/index.mdx
src/pages/getting-started/developer-sdk/index.mdx

Hide monitoring docs

---

src/pages/authorization/index.mdx
src/pages/getting-started/app-guides/app-webhooks/index.mdx
src/pages/monetization/how-to-monetize-apps/index.mdx
src/pages/monetization/index.mdx

Text rename

---

src/configs/containers.json
src/pages/data-reporting/app-monitoring/index.mdx
src/pages/getting-started/developer-sdk/index.mdx

Show App Monitoring docs

---

_redirects
src/constants/header.js
src/pages/getting-started/app-guides/helpdesk-widgets/index.mdx
src/pages/getting-started/helpdesk-apps/helpdesk-api/index.mdx
src/pages/monetization/app-review-process/index.mdx

Changed links, added HD info

---

src/pages/monetization/partner-program-api/index.mdx

- [PP-9592](https://livechatinc.atlassian.net/browse/PP-9592)
[PP-9592]: https://livechatinc.atlassian.net/browse/PP-9592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pp 9592/pp api leads

---

src/pages/monetization/partner-program-api/index.mdx

PP-9406/pp-api-search-campaigns

---

src/pages/extending-chat-widget/customer-sdk/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-3417)
Updating docs for customer-sdk after recent 4.0.2 release.

[CW-3417] Update customer-sdk docs

---

src/pages/extending-chat-widget/javascript-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-3497)
PR dedicated to adding a simplified `trigger_sales_tracker` method to our docs. This method was never published before, that's why we decided to simplify it a bit and then list in in our JS API docs in the current and stable API version. Methods also lists the possible parameters and links to a dedicated article in LC's Help Center.

Add new simplified trigger_sales_tracker method to JS API docs

---

src/pages/extending-chat-widget/chat-widget-moments/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-3501)
Update Chat Widget Moments docs after recent release of `moments-sdk` which adds customer's `groupId` to `LauncherData`

Update Chat Widget Moments docs with new groupId property

---

src/pages/getting-started/api-pricing/index.mdx

Pricing change fix

---

src/pages/getting-started/index.mdx

Remove API usage guide link

---

src/pages/extending-chat-widget/custom-identity-provider/index.mdx
src/pages/monetization/app-review-process/index.mdx

Link and naming fixes

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-10085)

PP-10102: document GET /v2/partners/solutions/licenses/search/csv endpoint

---

src/pages/getting-started/developer-sdk/index.mdx

(NO-DPS) Developer SDK patch v1.3.63

---

next-sitemap.config.js
next-sitemap.js
package-lock.json
package.json

Update version of next-sitemap lib

---

src/pages/messaging/references/default-properties/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-13293)
Add event prop `chats.formatting`.

API-13293: Document event prop chats.formatting

---

src/pages/getting-started/api-pricing/index.mdx

Update API pricing and info

---

src/pages/getting-started/app-guides/app-webhooks/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/MP-1658)
Adds new payment trial started webhook.

Add docs for payment_trialstarted app webhooks

---

src/pages/monetization/partner-program-api/index.mdx

PP-10253: Example extended with helpdesk

---

src/components/core/seo.js

(HOTFIX) canonical url

---

next.config.js

add trailing slash

---

payloads/management/v3.5/configuration-api/responses/bots/getBot.json
payloads/management/v3.5/configuration-api/responses/bots/listBotTemplates.json
payloads/management/v3.5/configuration-api/responses/bots/listBots.json

Bot's avatar is under `avatar` prop

fix bot's avatar path

---

next.config.js
src/components/core/seo.js

(hotfix) delete trailing slash, update canonical links

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira PP-10538](https://livechatinc.atlassian.net/browse/PP-10538)

PP-10538 max trial duration for LC campaigns set to 30

---

src/pages/monetization/partner-program-api/index.mdx

- [PP-10570](https://livechatinc.atlassian.net/browse/PP-10570)
[PP-10570]: https://livechatinc.atlassian.net/browse/PP-10570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PP-10570 get partner commission report

---

src/pages/monetization/partner-program-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-10407)

PP-10561: update Get Earnings Metrics

---

src/pages/monetization/partner-program-api/index.mdx

PP-10406: Add missing docs

---

src/pages/monetization/partner-program-api/index.mdx

PP-10553: Update Partner Program API docs by

---

src/pages/monetization/partner-program-api/index.mdx

PP-10573: Corrections

---

src/pages/extending-chat-widget/javascript-api/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-2737)

Add docs for new param in widget's js API

---

src/pages/extending-chat-widget/chat-widget-moments/index.mdx

[https://deploy-preview-1489--livechat-public-docs.netlify.app/](https://deploy-preview-1489--livechat-public-docs.netlify.app/extending-chat-widget/chat-widget-moments#updatecustomerdata
)
- [Jira](https://livechatinc.atlassian.net/browse/CW-3669)
Add updateCustomerData description to moments docs

[CW-3669] Add updateCustomerData to Moments docs

---

src/components/core/seo.js

(NO-DPS) Update metadata

---

src/configs/containers.json
src/constants/header.js
src/pages/getting-started/developer-cli/index.mdx

Docs for DevCLI

---

src/pages/extending-agent-app/products-sdk/agent-app-sdk/index.mdx

(NO-DPS) Navigate and Set filter methods in Agent App SDK

---

payloads/management/v3.5/configuration-api/index.js
payloads/management/v3.5/configuration-api/responses/properties/listGroupProperties.json
payloads/management/v3.5/configuration-api/responses/properties/listGroupsProperties.json
payloads/management/v3.6/configuration-api/index.js
payloads/management/v3.6/configuration-api/responses/properties/listGroupProperties.json
payloads/management/v3.6/configuration-api/responses/properties/listGroupsProperties.json
src/constants/index.js
src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

- [Jira API-13544](https://livechatinc.atlassian.net/browse/API-13544)
- [Jira API-13545](https://livechatinc.atlassian.net/browse/API-13545)
Fix various small docs issues reported by the product.

API-13544, API-13545: fixes

---

package-lock.json
package.json
src/pages/_app.js

delete store metrics

---

src/pages/monetization/app-review-process/index.mdx

(DPS-4303) Remove mentions of Paid app review

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx

N/A
Fixed typo of missing `"` character in example payload for issuing bot token. `bot_secret` field was affected.

Fix typo in payload for "issue bot token"

---

src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.3/index.mdx
src/pages/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

(NO-DPS) Docs fixes 08-2024

---

src/pages/extending-chat-widget/customer-sdk/index.mdx
src/pages/messaging/customer-chat-api/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.4/index.mdx
src/pages/messaging/customer-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.6/rtm-reference/index.mdx

Add missing information from Slack channels

---

src/pages/extending-agent-app/products-sdk/agent-app-sdk/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/PP-10584)
Added docs for createSettingsWidget

PP-10584 add settings widget docs

---

src/pages/_app.js

(NO-DPS) GTM change

---

src/configs/redoc/global-accounts-api/spec.yml

Update Global Accounts API

---

src/pages/getting-started/installing-livechat/android-widget/index.mdx

LiveChat for Android v2.3.4

---

src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/API-13733)

API-13733: agent-api: add update_session.

---

src/components/core/Page/header.js
src/utils/index.js

implement slugified ids for document titles

---

src/components/core/Page/header.js

change ids placement

---

src/pages/extending-chat-widget/custom-identity-provider/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/CW-3899)
Fixing typo in custom identity provider docs

typo in custom identity provider docs

---

src/components/core/Page/header.js

adjust headings for algolia search

---

src/pages/getting-started/installing-livechat/android-widget/index.mdx

Update Android SDK docs

---

src/pages/index.js

(DPS-4375) Change |text to Text in the documentation

---

src/pages/getting-started/installing-livechat/android-widget/index.mdx

Update chat window android version

---

src/configs/redoc/chat-api/spec-rtm.yml
src/configs/redoc/chat-api/spec.yml

New methods in TeamChat API

---

src/pages/getting-started/installing-livechat/android-widget/index.mdx

Update android widget error handling section and version

---

src/configs/redoc/global-accounts-api/spec.yml
src/pages/authorization/agent-authorization/index.mdx
src/pages/default-credentials.md

Remove prefix from refresh tokens

---

src/pages/getting-started/installing-livechat/ios-widget/index.mdx
src/pages/messaging/agent-chat-api/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.3/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-pushes/index.mdx
src/pages/messaging/references/system-messages/index.mdx

Update LiveChat for iOS docs + misc fixes

---

src/pages/monetization/app-review-process/index.mdx

Add new app quality requirements

---

.github/workflows/commitlint.yml
.github/workflows/release.yml
.husky/commit-msg
.releaserc.json
README.md
commitlint.config.js
package-lock.json
package.json

(DPS-4422) Add versioning to livechat-public-docs

---

src/pages/_app.js

(NO-DPS) delete unused import in _app.js file

---

src/pages/index.js

fix: delete unused import in pages/index.js file

---

commitlint.config.js

fix: update commitlint.config.js, increase foot max line length

---

.github/pull_request_template.md

fix: update pull request template to match new requirements

---

src/components/core/seo.js

feat: migrate chat widget to production

---

src/components/core/Search/index.js
src/constants/index.js

- [Jira](https://livechatinc.atlassian.net/browse/DPS-4431)
These changes aim to clarify search results for certain phrases. Special attention should be given to phrases like send_event.
Previous results:
After change results:

fix: search do not display to what relates displayed method (DPS-4431) 

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v2.0/index.mdx
src/pages/management/configuration-api/v3.2/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.4/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.2/index.mdx
src/pages/messaging/agent-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.3/index.mdx
src/pages/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.4/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/index.mdx
src/pages/messaging/customer-chat-api/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.2/index.mdx
src/pages/messaging/customer-chat-api/v3.2/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.3/index.mdx
src/pages/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.4/index.mdx
src/pages/messaging/customer-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.6/index.mdx
src/pages/messaging/customer-chat-api/v3.6/rtm-reference/index.mdx

Update data center information

---

src/pages/getting-started/installing-livechat/android-widget/index.mdx

Update chat window android version, remove obsolete sample app images

---

src/constants/index.js
src/pages/data-reporting/index.mdx
src/pages/data-reporting/reports-api/v3.3/index.mdx
src/pages/management/configuration-api/v3.3/index.mdx
src/pages/management/index.mdx
src/pages/messaging/agent-chat-api/v3.3/index.mdx
src/pages/messaging/agent-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/v3.3/index.mdx
src/pages/messaging/customer-chat-api/v3.3/rtm-reference/index.mdx
src/pages/messaging/index.mdx

Deprecate 3.3 APIs

---

payloads/messaging/v3.6/agent-chat-api/events/system.json
payloads/messaging/v3.6/agent-chat-api/index.js
payloads/messaging/v3.6/customer-chat-api/events/system.json
payloads/messaging/v3.6/customer-chat-api/index.js
src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.6/data-structures/index.mdx
src/pages/messaging/customer-chat-api/changelog/index.mdx
src/pages/messaging/customer-chat-api/v3.6/data-structures/index.mdx

Jira: https://livechatinc.atlassian.net/browse/CDP-56

feat: add new system event in v3.6

---

src/pages/monetization/app-review-process/index.mdx

Add new app review sections

---

CONTRIBUTING.md
src/components/core/seo.js
src/pages/extending-chat-widget/customer-sdk/index.mdx
src/pages/extending-chat-widget/customer-sdk/v2.0/index.mdx
src/pages/extending-chat-widget/customer-sdk/v3.0/index.mdx

Fix(docs): fix support license number

---

src/pages/management/configuration-api/index.mdx
src/pages/management/configuration-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.4/rtm-reference/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx

feat(docs): update bot related apis

---

src/pages/messaging/agent-chat-api/changelog/index.mdx
src/pages/messaging/agent-chat-api/v3.6/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-pushes/index.mdx
src/pages/messaging/agent-chat-api/v3.6/rtm-reference/index.mdx
src/pages/messaging/customer-chat-api/changelog/index.mdx
src/pages/messaging/customer-chat-api/v3.6/rtm-pushes/index.mdx

- [Jira](https://livechatinc.atlassian.net/browse/ME-508)

messaging: add thinking_indicator

---

_redirects
src/pages/guides/index.mdx

Add missing redirects

---

_redirects
src/configs/containers.json
src/pages/guides/mcp/index.mdx

Add MCP guide
